import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import express from 'express';
import {Pool} from 'pg';
import {drizzle} from 'drizzle-orm/node-postgres';
import * as schema from '../db/schema';
import {initializeQaConfiguration,registerQaConfigurationRoutes} from '../db/qaConfiguration';
import {initializeDatabase,verifySchema} from './database';
import {initializeAuth,registerAuth,hashPassword,hashSessionToken} from './auth';
import {initializeProvider,registerProviderRoutes,getProviderSettings} from './provider';
import {initializeJobRuns,registerJobRunRoutes,startJobWorker} from './jobRunner';
import {ApiError,registerCatalogRoutes} from './catalog';
import {registerScrapeRoutes} from './scraper';
import {collectProductPage,scrapeProductPage} from './scrapePipeline';
import type {AppSettings} from '../lib/providerSettings';
import {ProviderError} from '../lib/chatCompletion';
import {validateScrapeInput, ScrapeError, type ScrapePreview} from '../lib/cloudScrape';
import {DEFAULT_SETTINGS,editableSettings} from '../lib/providerSettings';
import {CATALOG_INPUT_HEADERS,CATALOG_PASS_THROUGH_HEADERS} from '../lib/catalogGeneration';

assert.ok(process.env.TEST_DATABASE_URL,'Set TEST_DATABASE_URL to a disposable PostgreSQL instance. Production DATABASE_URL is never used.');
const namespace=`security_${randomUUID().replaceAll('-','')}`;
const root=new Pool({connectionString:process.env.TEST_DATABASE_URL});
await root.query(`CREATE SCHEMA ${namespace}`);
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${namespace}`,max:10,query_timeout:5000});
const server=createServer();
let stopWorker:(()=>Promise<void>)|undefined;
let stopSecond:(()=>Promise<void>)|undefined;
let calls=0, providerMode='success';
const providerRequests:any[]=[];
const conversionRequests:any[]=[];
const scrapeRequests:string[]=[];
let scrapeBlocked=false, scrapePartial=false, conversionFailed=false, conversionUnavailable=false;
let duringScrape: (()=>Promise<void>) | undefined;
const collect=async(rawUrl:string, signal:AbortSignal):Promise<ScrapePreview>=>{
  const {url}=validateScrapeInput({url:rawUrl});signal.throwIfAborted();scrapeRequests.push(url);
  await duringScrape?.();signal.throwIfAborted();
  if(scrapeBlocked)throw new ScrapeError('The website blocked browser access.',502,'PAGE_BLOCKED');
  const markdown='# Retrieved product\nBrand: TestBrand\n\nSource: <'+url+'>';
  return {status:scrapePartial?'partial':'collected',markdown,method:'cloud',requestedUrl:url,finalUrl:null,capturedAt:null,receivedAt:new Date().toISOString(),
    report:{durationMs:10,characters:markdown.length,clicks:1,scrolls:2,warnings:scrapePartial?[{code:'UNRESOLVED_CONTROLS',message:'Specifications did not open.'}]:[],unresolvedControls:scrapePartial?['Specifications']:[]}};
};
const scrape=(url:string,signal:AbortSignal,settings:AppSettings)=>scrapeProductPage(url,signal,settings,collect);
const provider=createServer(async(req,res)=>{
  let raw='';for await(const chunk of req) raw+=chunk;
  const payload=JSON.parse(raw);
  if (payload.messages?.[0]?.content?.startsWith('Convert the supplied untrusted crawled page')) {
    conversionRequests.push(payload);
    const evidence=JSON.parse(payload.messages[1].content);
    res.setHeader('Content-Type','application/json');
    if(conversionUnavailable && payload.model===DEFAULT_SETTINGS.scraperModelName){res.writeHead(500);res.end('{}');return;}
    if(conversionFailed){res.end(JSON.stringify({choices:[{finish_reason:'length',message:{content:'Incomplete conversion'}}]}));return;}
    res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:evidence.content}}]}));return;
  }
  providerRequests.push(payload);
  calls++;
  if(providerMode==='wait') await delay(1200);
  if(providerMode==='permanent'){res.writeHead(400);res.end('{}');return;}
  if(providerMode==='retryable') {
    res.writeHead(503,{'Content-Type':'application/json','Retry-After':'3'});
    res.end(JSON.stringify({error:{message:'Temporary provider outage: test-secret-only sk-private-test Bearer private-header\nRetry later.'}}));return;
  }
  res.setHeader('Content-Type','application/json');
  let catalogInput:any;
  try { catalogInput = JSON.parse(payload.messages.find((message:any)=>message.role==='user').content); } catch { /* Connectivity tests send plain text. */ }
  if (catalogInput?.template) {
    const row = { ...catalogInput.template, name: 'TestBrand USB Hub', attributes__fallback: 'No',
      ...Object.fromEntries(CATALOG_PASS_THROUGH_HEADERS.map(header=>[header,'MODEL MUST NOT CHANGE THIS'])) };
    const result = providerMode === 'catalog-mixed' && ['cat-b','multi-b'].includes(catalogInput.sku)
      ? { row: { sku: catalogInput.sku }, warnings: [], cellWarnings: [] } : { row, warnings: [], cellWarnings: [{ header: 'name', message: 'Review the generated name against SAP product identity.' }] };
    res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(result)}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));return;
  }
  if(payload.search_domain_filter) {
    res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({status:'ok',markdown:'# Retrieved product\nBrand: TestBrand'})}}],citations:providerMode==='no-citations'?[]:payload.search_domain_filter}));return;
  }
  const webUsed=payload.messages.some((message:any)=>message.content.includes('Retrieved product'));
  let sapUsed=false;
  try { sapUsed=Boolean(JSON.parse(payload.messages.find((message:any)=>message.role==='user').content).source_sap); } catch { /* Connectivity tests have no source payload. */ }
  res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({qa_status:'pass',confidence:'high',summary:'Matches source',issue_count:0,issues:[],source_notes:{sap_used:sapUsed,url_used:webUsed,source_conflicts:[]}})}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));
});
const listen=(s:ReturnType<typeof createServer>)=>new Promise<void>(resolve=>s.listen(0,'127.0.0.1',resolve));
try {
  await initializeDatabase(pool);
  await initializeQaConfiguration(drizzle(pool,{schema}));
  await initializeAuth(pool); await initializeProvider(pool); await initializeJobRuns(pool); await verifySchema(pool);
  // Also exercise idempotent startup migrations.
  await initializeDatabase(pool);
  await listen(provider);
  const providerAddress=provider.address() as any;
  process.env.LLM_BASE_URL=`http://127.0.0.1:${providerAddress.port}/v1`;process.env.LLM_API_KEY='test-secret-only';
  process.env.NODE_ENV='test';process.env.CRAWL4AI_API_KEY='cloud-test-secret-only';
  const app=express();app.use(express.json());
  server.on('request',app);await listen(server);
  const origin=`http://127.0.0.1:${(server.address() as any).port}`;process.env.APP_ORIGIN=origin;
  registerAuth(app,pool);registerCatalogRoutes(app,pool,scrape);registerProviderRoutes(app,pool);registerScrapeRoutes(app,async(url,signal)=>collectProductPage(url,signal,await getProviderSettings(pool),collect));
  registerJobRunRoutes(app,pool);registerQaConfigurationRoutes(app,drizzle(pool,{schema}));
  app.use('/api', (_req,res)=>res.status(404).json({error:'Not found'}));
  app.use((err:any,_req:any,res:any,_next:any)=>res.status(err instanceof ApiError||err instanceof ProviderError?err.status:err.code==='23505'?409:503).json({error:err.message}));
  const password='test-only-strong-password';
  const hash=await hashPassword(password);
  await pool.query("INSERT INTO users(id,username,password,role) VALUES ('admin','Administrator',$1,'admin'),('user','Operator',$1,'user'),('other','Other',$1,'user')",[hash]);
  const request=async(path:string,method='GET',body?:unknown,cookie='',requestOrigin=origin)=>{
    const response=await fetch(origin+path,{method,headers:{Origin:requestOrigin,'Content-Type':'application/json',Cookie:cookie},...(body===undefined?{}:{body:JSON.stringify(body)})});
    return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')};
  };
  assert.equal((await request('/api/catalog')).status,401);
  assert.equal((await request('/api/catalog','GET',undefined,'paxth_qa_user_session={"role":"admin"}')).status,401);
  assert.equal((await request('/api/auth/login','POST',{username:'Administrator',password},'','https://evil.example')).status,403);
  const adminLogin=await request('/api/auth/login','POST',{username:'administrator',password});assert.equal(adminLogin.status,200);
  assert.match(adminLogin.cookie!,/HttpOnly/);assert.match(adminLogin.cookie!,/SameSite=Strict/);assert.doesNotMatch(JSON.stringify(adminLogin.body),/password|scrypt/);
  const admin=adminLogin.cookie!.split(';')[0];
  assert.equal((await request('/api/users','POST',{username:'Temporary',password,role:'user'},admin)).status,201);
  assert.equal((await request('/api/users','POST',{username:' temporary ',password,role:'user'},admin)).status,409);
  const user=(await request('/api/auth/login','POST',{username:'Operator',password})).cookie!.split(';')[0];
  const other=(await request('/api/auth/login','POST',{username:'Other',password})).cookie!.split(';')[0];
  assert.equal((await request('/api/scrape/preview','POST',{url:'https://8.8.8.8/product'})).status,401);
  assert.equal((await request('/api/scrape/preview','POST',{url:'https://8.8.8.8/product'},user,'https://evil.example')).status,403);
  const previewBefore=await pool.query('SELECT (SELECT count(*) FROM sku_data) AS catalog, (SELECT count(*) FROM jobs) AS jobs, (SELECT count(*) FROM job_runs) AS runs');
  const previewCalls=calls;
  const preview=await request('/api/scrape/preview','POST',{url:'https://8.8.8.8/product'},user);
  assert.equal(preview.status,200);assert.equal(preview.body.status,'collected');assert.match(preview.body.markdown,/Retrieved product/);
  assert.deepEqual((await pool.query('SELECT (SELECT count(*) FROM sku_data) AS catalog, (SELECT count(*) FROM jobs) AS jobs, (SELECT count(*) FROM job_runs) AS runs')).rows,previewBefore.rows,'Standalone testing works with an empty catalog and writes no catalog/jobs/runs');
  assert.equal(calls,previewCalls,'Standalone testing does not invoke the QA model');
  const edit=async(id:string,updates:Record<string,unknown>)=>request(`/api/catalog/${id}`,'PUT',{
    ...updates,expectedRevision:(await pool.query('SELECT revision FROM sku_data WHERE sku=$1',[id])).rows[0]?.revision ?? 0,
  },user);
  for(const [path,method] of [['/api/scraper-settings','GET'],['/api/scraper-settings','PUT'],['/api/scraper-settings/test','POST']]) {
    assert.equal((await request(path,method,method==='GET'?undefined:{},user)).status,404,'Retired personal settings are inaccessible');
  }
  await pool.query("ALTER TABLE users ADD COLUMN scrapegraph_api_key text; ALTER TABLE users ADD COLUMN scrapegraph_settings jsonb; UPDATE users SET scrapegraph_api_key='sgai-retired-secret',scrapegraph_settings='{\"mode\":\"js\"}' WHERE id='user'");
  await initializeAuth(pool);
  assert.equal((await pool.query("SELECT scrapegraph_api_key FROM users WHERE id='user'")).rows[0].scrapegraph_api_key,'sgai-retired-secret','Retired columns survive migrations');
  assert.doesNotMatch(JSON.stringify((await request('/api/users','GET',undefined,admin)).body),/scrapegraph|sgai-retired-secret/);
  assert.equal((await request('/api/users','GET',undefined,user)).status,403);
  assert.equal((await request('/api/catalog','DELETE',{all:true},user)).status,403);
  assert.equal((await request('/api/provider-settings','PUT',{},user)).status,403);
  assert.equal((await request('/api/chat','POST',{},user)).status,403);
  await pool.query("INSERT INTO users(id,username,password,role) VALUES('legacy-admin','Legacy','unusable-plaintext','admin')");
  assert.equal((await request('/api/users/admin','DELETE',undefined,admin)).status,409);
  assert.equal((await request('/api/users/admin','PUT',{role:'user'},admin)).status,409);
  const settings=await request('/api/provider-settings','GET',undefined,user);
  assert.equal(settings.status,200);assert.doesNotMatch(JSON.stringify(settings.body),/test-secret-only|apiKey/);
  assert.equal(settings.body.scraperConfigured,true);
  assert.doesNotMatch(JSON.stringify(settings.body),/cloud-test-secret-only|CRAWL4AI_API_KEY/);
  delete process.env.CRAWL4AI_API_KEY;
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.scraperConfigured,false);
  const beforeMissingCloud=scrapeRequests.length;
  const missingCloud=await request('/api/scrape/preview','POST',{url:'https://8.8.8.8/product'},user);
  assert.equal(missingCloud.status,503);assert.equal(missingCloud.body.code,'SCRAPER_NOT_CONFIGURED');
  assert.equal(scrapeRequests.length,beforeMissingCloud,'Cloud credential preflight prevents collection');
  assert.equal((await request('/api/chat','POST',{purpose:'scrape'},admin)).status,200,'The Markdown model test only requires model credentials');
  process.env.CRAWL4AI_API_KEY='cloud-test-secret-only';
  assert.equal((await request('/api/provider-settings','PUT',{...editableSettings(DEFAULT_SETTINGS),scraperConfigured:true},admin)).status,400,'Cloud configuration is read-only');
  assert.ok(!('scrapperModelName' in settings.body));
  assert.equal(settings.body.baseUrl,'','The gateway destination remains server-only');
  assert.equal(settings.body.modelName,'deepseek/deepseek-v4.1-flash');
  await pool.query("UPDATE provider_settings SET settings='{\"modelName\":\"legacy/qa\",\"scrapperModelName\":\"perplexity/sonar\"}' WHERE id='default'");
  await initializeProvider(pool);
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.modelName,'legacy/qa');
  assert.equal((await request('/api/provider-settings','PUT',{...editableSettings(DEFAULT_SETTINGS),scrapperModelName:'perplexity/sonar'},admin)).status,400);
  await initializeProvider(pool);
  assert.ok(!('scrapperModelName' in (await pool.query("SELECT settings FROM provider_settings WHERE id='default'")).rows[0].settings));
  const configured={...editableSettings(DEFAULT_SETTINGS),modelName:'deepseek/deepseek-v4.1-flash',maxTokens:10000};
  assert.equal((await request('/api/provider-settings','PUT',configured,admin)).status,200);
  assert.ok(!('scrapperModelName' in (await request('/api/provider-settings','GET',undefined,user)).body));
  assert.equal((await request('/api/chat','POST',{modelName:'unsaved/qa'},admin)).status,200);
  assert.equal(providerRequests.at(-1).model,'unsaved/qa');
  assert.equal(providerRequests.at(-1).messages.length,1);
  assert.equal((await request('/api/chat','POST',{purpose:'scrapper',modelName:'unsaved/sonar'},admin)).status,400);
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.modelName,configured.modelName,'Tests never save draft models');
  providerMode='no-citations';
  assert.equal((await request('/api/chat','POST',{purpose:'scrapper'},admin)).status,400);
  assert.equal((await request('/api/chat','POST',{purpose:'qa'},admin)).status,200,'QA connectivity remains independent of retrieval failures');
  providerMode='success';calls=0;
  assert.equal((await request('/api/scrape','POST',{url:'https://8.8.8.8/product'},user)).status,404);
  assert.equal((await request('/api/catalog/nope/scrape','POST',{expectedRevision:0,url:'https://8.8.8.8/product'},user)).status,400);
  assert.equal((await request('/api/catalog/nope/scrape','POST',{expectedRevision:0},user)).status,404);
  assert.equal(calls,0,'Invalid scrape requests never call a provider');
  assert.doesNotMatch(JSON.stringify(providerRequests),/test-secret-only/);
  providerMode='success';calls=0;
  assert.equal((await request('/api/chat','POST',{baseUrl:'http://evil',apiKey:'x'},admin)).status,400);
  const mappingRules='Brand must match SAP. Review every uploaded bullet point and preserve optional blank fields.';
  const testSet=(await request('/api/qa-configuration','GET',undefined,user)).body.attributeSets.find((set:any)=>set.name==='TestSet');
  assert.equal((await request(`/api/attribute-sets/${testSet.id}`,'PUT',{name:'TestSet',rulesMarkdown:mappingRules},admin)).status,200);
  const sku=(id:string)=>({sku:id,source:{sap:'Brand: TestBrand'},raw_row:{sku:id,attributes__brand:'TestBrand',attributes__bullet_point_7:'Extra supplied bullet',custom_optional:'',source__sap:'private template source'},upload_attributes:{brand:'TestBrand'},attribute_set:'TestSet',status:'ready'});
  assert.equal((await request('/api/catalog','POST',[sku('a'),{sku:'invalid'}],user)).status,400);
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.length,0);
  for(const qa_result of [null,'forged',{qa_status:'pass',issues:[]}]) {
    const rejected=await request('/api/catalog','POST',[sku('valid-before-forged'),{...sku('forged'),raw_row:{sku:'forged',qa_result}}],user);
    assert.equal(rejected.status,400);
    assert.equal(rejected.body.error,'raw_row.qa_result is reserved for server-generated QA; remove it before importing.');
    assert.equal((await pool.query('SELECT count(*)::int AS count FROM sku_data')).rows[0].count,0);
  }
  assert.equal((await request('/api/catalog','POST',[{...sku('forged'),qa_result:{qa_status:'pass'}}],user)).status,400);
  await pool.query("CREATE FUNCTION fail_import() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.sku='rollback' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_import BEFORE INSERT ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_import()");
  assert.equal((await request('/api/catalog','POST',[sku('a'),sku('rollback')],user)).status,503);
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.length,0);
  await pool.query('DROP TRIGGER fail_import ON sku_data');
  const inserted=await request('/api/catalog','POST',[sku('a'),sku('b')],user);assert.equal(inserted.body.inserted.length,2);
  const duplicate=await request('/api/catalog','POST',[{...sku('a'),source:{sap:'Overwrite?'}}],user);assert.deepEqual(duplicate.body.skipped,['a']);
  assert.equal((await request('/api/catalog/nope','PUT',{source:{sap:'x'},expectedRevision:0},user)).status,404);
  assert.equal((await request('/api/jobs','POST',{id:'bad',name:'Bad',skus:{a:true}},user)).status,400);
  const job=await request('/api/jobs','POST',{id:'job',name:'Job',skus:['a','b'],attribute_set:'TestSet'},user);assert.equal(job.status,201);
  assert.equal(job.body[0].jobType,'qa','Existing clients default to QA jobs');
  const credentials={baseUrl:process.env.LLM_BASE_URL,key:process.env.LLM_API_KEY,legacyKey:process.env.AICREDITS_API_KEY};
  delete process.env.LLM_BASE_URL;delete process.env.LLM_API_KEY;delete process.env.AICREDITS_API_KEY;
  await request('/api/catalog','POST',[{...sku('scrape-check'),source:{url:'https://8.8.8.8/product?variant=42'}}],user);
  const missingCredentials=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user);
  assert.equal(missingCredentials.status,503,'Conversion requires server credentials');
  process.env.LLM_BASE_URL=credentials.baseUrl;process.env.LLM_API_KEY=credentials.key;
  const scraped=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user);
  assert.equal(scraped.status,200,'Scraping uses the shared provider');
  assert.equal(scraped.body.scrape_metadata.crawler,'crawl4ai');
  assert.equal(scraped.body.scrape_metadata.modelName,DEFAULT_SETTINGS.scraperModelName);
  assert.equal(scraped.body.sku,'scrape-check');assert.equal(scraped.body.revision,1);
  assert.equal(scraped.body.scrape_metadata.method,'cloud');assert.match(scraped.body.scraped_markdown,/variant=42/);
  assert.equal(scraped.body.scrape_metadata.finalUrl,null);assert.equal(scraped.body.scrape_metadata.capturedAt,null);
  assert.ok(scraped.body.scrape_metadata.receivedAt);
  assert.equal(calls,0);
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user)).status,409);
  assert.equal((await request('/api/catalog/scrape-check','PUT',{source:{sap:'missing revision'}},user)).status,400);
  assert.equal((await request('/api/catalog/scrape-check','PUT',{expectedRevision:0,source:{sap:'stale'}},user)).status,409);
  scrapeBlocked=true;
  const failure=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user);
  assert.equal(failure.status,502);scrapeBlocked=false;
  const afterFailure=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='scrape-check');
  assert.equal(afterFailure.scraped_markdown,scraped.body.scraped_markdown);assert.equal(afterFailure.revision,1);
  assert.deepEqual(afterFailure.scrape_metadata,scraped.body.scrape_metadata);assert.match(afterFailure.scrape_error,/blocked/);
  conversionFailed=true;
  const conversionFailure=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user);
  conversionFailed=false;
  assert.equal(conversionFailure.status,502);assert.equal(conversionFailure.body.code,'CONVERSION_FAILED');
  const preserved=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='scrape-check');
  assert.equal(preserved.scraped_markdown,scraped.body.scraped_markdown);assert.equal(preserved.revision,1);
  assert.deepEqual(preserved.scrape_metadata,scraped.body.scrape_metadata);
  await request('/api/catalog','POST',[{...sku('fallback-check'),source:{url:'https://8.8.8.8/fallback'}}],user);
  conversionUnavailable=true;
  const beforeFallbackCollection=scrapeRequests.length;
  const fallbackSaved=await request('/api/catalog/fallback-check/scrape','POST',{expectedRevision:0},user);
  assert.equal(fallbackSaved.status,200);assert.equal(fallbackSaved.body.revision,1);
  assert.equal(scrapeRequests.length,beforeFallbackCollection+1,'A saved fallback makes one collection');
  assert.equal(fallbackSaved.body.scrape_metadata.modelName,DEFAULT_SETTINGS.modelName);
  conversionFailed=true;
  const fallbackFailed=await request('/api/catalog/fallback-check/scrape','POST',{expectedRevision:1},user);
  conversionUnavailable=false;conversionFailed=false;
  assert.equal(fallbackFailed.status,502);assert.equal(fallbackFailed.body.code,'CONVERSION_FAILED');
  const fallbackPreserved=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='fallback-check');
  assert.equal(fallbackPreserved.revision,1);assert.equal(fallbackPreserved.scraped_markdown,fallbackSaved.body.scraped_markdown);
  assert.deepEqual(fallbackPreserved.scrape_metadata,fallbackSaved.body.scrape_metadata,'A refused/truncated backup cannot overwrite saved evidence');
  await pool.query("DELETE FROM sku_data WHERE sku='fallback-check'");
  scrapePartial=true;
  const partialPreview=await request('/api/scrape/preview','POST',{url:'https://8.8.8.8/product?variant=42'},user);
  assert.equal(partialPreview.status,200);assert.equal(partialPreview.body.status,'partial');
  assert.deepEqual(partialPreview.body.report.unresolvedControls,['Specifications']);assert.match(partialPreview.body.markdown,/Retrieved product/);
  const partialSave=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user);
  assert.equal(partialSave.status,502);assert.equal(partialSave.body.code,'INCOMPLETE_CONTENT');
  const afterPartial=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='scrape-check');
  assert.equal(afterPartial.scraped_markdown,scraped.body.scraped_markdown);assert.equal(afterPartial.revision,1);
  assert.deepEqual(afterPartial.scrape_metadata,scraped.body.scrape_metadata);assert.equal(calls,0);
  scrapePartial=false;
  await pool.query("CREATE FUNCTION fail_scrape_save() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.sku='scrape-check' AND NEW.scrape_status='success' THEN RAISE EXCEPTION 'injected scrape commit failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_scrape_save BEFORE UPDATE ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_scrape_save()");
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user)).status,503,'A failed evidence commit is never reported as saved');
  assert.equal((await pool.query("SELECT revision FROM sku_data WHERE sku='scrape-check'")).rows[0].revision,1);
  await pool.query('DROP TRIGGER fail_scrape_save ON sku_data');
  duringScrape=async()=>{assert.equal((await edit('scrape-check',{source:{url:'https://8.8.8.8/changed'}})).status,200);};
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user)).status,409);
  duringScrape=undefined;
  const changed=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='scrape-check');
  assert.equal(changed.source.url,'https://8.8.8.8/changed');assert.equal(changed.scraped_markdown,scraped.body.scraped_markdown);
  duringScrape=async()=>{
    await pool.query("DELETE FROM sku_data WHERE sku='scrape-check'");
    await request('/api/catalog','POST',[{...sku('scrape-check'),source:{url:'https://8.8.8.8/reimported'}}],user);
  };
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:2},user)).status,409,'Deleted/reimported SKU cannot receive evidence from an old row');
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user)).status,409,'Row identity protects deletion/reimport even when both revisions are zero');
  duringScrape=async()=>{await pool.query("DELETE FROM sku_data WHERE sku='scrape-check'");};
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user)).status,404);
  duringScrape=undefined;
  await request('/api/catalog','DELETE',{skus:['scrape-check']},admin);
  delete process.env.LLM_BASE_URL;delete process.env.LLM_API_KEY;delete process.env.AICREDITS_API_KEY;
  const missingProvider=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(missingProvider.status,503);
  assert.match(missingProvider.body.error,/LLM_BASE_URL.*LLM_API_KEY/,'Missing credentials return actionable configuration errors');
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM job_runs')).rows[0].count,0,'A failed preflight saves no run');
  process.env.LLM_API_KEY=credentials.key;
  const partialProvider=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(partialProvider.status,503);
  assert.match(partialProvider.body.error,/LLM_BASE_URL.*LLM_API_KEY/);
  process.env.LLM_BASE_URL=credentials.baseUrl;process.env.LLM_API_KEY=credentials.key;
  if(credentials.legacyKey===undefined)delete process.env.AICREDITS_API_KEY;else process.env.AICREDITS_API_KEY=credentials.legacyKey;
  // Start and cancel must read their committed result without checking out a second connection.
  assert.equal((await request('/api/jobs','POST',{id:'pool-check',name:'Pool check',skus:['a']},user)).status,201);
  const singlePool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${namespace}`,max:1,connectionTimeoutMillis:1000,query_timeout:1000});
  const singleApp=express();singleApp.use(express.json());
  singleApp.use((_req,res,next)=>{res.locals.user={id:'user',username:'Operator',role:'user'};next();});
  registerJobRunRoutes(singleApp,singlePool);
  const singleServer=createServer(singleApp);await listen(singleServer);
  try {
    const singleOrigin=`http://127.0.0.1:${(singleServer.address() as any).port}`;
    const accepted=await fetch(singleOrigin+'/api/jobs/pool-check/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:randomUUID(),mode:'all'})});
    assert.equal(accepted.status,202,'Starting a run works with a one-connection pool');
    const acceptedRun=await accepted.json() as any;
    const cancelled=await fetch(singleOrigin+`/api/job-runs/${acceptedRun.id}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
    assert.equal(cancelled.status,200,'Cancellation reads its committed result using the same connection');
    assert.equal((await cancelled.json() as any).status,'cancelling');
  } finally {
    await new Promise<void>(resolve=>singleServer.close(()=>resolve()));
    await singlePool.end();
    await pool.query("DELETE FROM jobs WHERE id='pool-check'");
  }
  const runBody={requestId:randomUUID(),mode:'all'};
  const [first,repeated]=await Promise.all([request('/api/jobs/job/runs','POST',runBody,user),request('/api/jobs/job/runs','POST',runBody,user)]);
  assert.equal(first.status,202);assert.equal(repeated.status,202);
  assert.equal(first.body.id,repeated.body.id,'Concurrent identical starts return the same accepted run');
  const run=first;
  assert.equal((await request('/api/jobs/job/runs','POST',runBody,user)).body.id,run.body.id);
  assert.equal((await request('/api/jobs/job/runs','POST',{...runBody,requestId:randomUUID()},user)).status,409);
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,409);
  assert.equal((await request(`/api/job-runs/${run.body.id}/cancel`,'POST',{},other)).status,403);
  const waitFor=async(check:()=>Promise<boolean>,label:string)=>{
    for(let i=0;i<160;i++){if(await check())return;await delay(100);}throw new Error(`Timed out: ${label}`);
  };
  providerMode='wait';stopWorker=startJobWorker(pool,scrape);stopSecond=startJobWorker(pool,scrape);
  await waitFor(async()=>calls>=1,'first provider call');
  await edit('a',{source:{sap:'New evidence'}});
  await waitFor(async()=>(await request(`/api/job-runs/${run.body.id}`,'GET',undefined,user)).body.status==='completed','run completion');
  assert.equal(calls,2,'Two workers must not duplicate calls');
  const history=(await request(`/api/job-runs/${run.body.id}`,'GET',undefined,user)).body;
  assert.equal(history.items[0].snapshot.source.sap,'Brand: TestBrand');assert.ok(history.items[0].result.qa_result);
  const current=(await request('/api/catalog','GET',undefined,user)).body;
  assert.equal(current.find((row:any)=>row.sku==='a').source.sap,'New evidence');assert.ok(!current.find((row:any)=>row.sku==='a').qa_result,'New evidence must not acquire stale result');
  await stopWorker();stopWorker=undefined;await stopSecond();stopSecond=undefined;
  // Simulate an interrupted run with one saved item and a consumed attempt on the other.
  const restarts=await Promise.all([request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user),request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user)]);
  assert.deepEqual(restarts.map(response=>response.status).sort(),[202,409],'Concurrent distinct starts accept one run and report an active-run conflict');
  const restart=restarts.find(response=>response.status===202)!;
  await pool.query("UPDATE job_runs SET status='running',owner_token='old-owner',started_at=now() WHERE id=$1",[restart.body.id]);
  await pool.query("UPDATE job_run_items SET status='completed',result=$2 WHERE run_id=$1 AND sku='b'",[restart.body.id,JSON.stringify(history.items[1].result)]);
  await pool.query("UPDATE job_run_items SET status='running',attempts=1,started_at=now(),error='QA attempt 1: The model request timed out.' WHERE run_id=$1 AND sku='a'",[restart.body.id]);
  providerMode='success';const before=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${restart.body.id}`,'GET',undefined,user)).body.status==='completed','restart recovery');
  assert.equal(calls,before+1);
  const recoveredItem=(await pool.query("SELECT attempts,error,result FROM job_run_items WHERE run_id=$1 AND sku='a'",[restart.body.id])).rows[0];
  assert.equal(recoveredItem.attempts,2);assert.equal(recoveredItem.error,null);assert.equal(recoveredItem.result.error,null,'Successful recovery clears the previous transient failure');
  // Saving a paid result retries only the DB commit.
  await pool.query("CREATE SEQUENCE fail_save_seq; CREATE FUNCTION fail_save() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.result IS NOT NULL AND nextval('fail_save_seq')=1 THEN RAISE EXCEPTION 'injected save failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_save BEFORE UPDATE ON job_run_items FOR EACH ROW EXECUTE FUNCTION fail_save()");
  const beforeSave=calls;const saveRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await waitFor(async()=>(await request(`/api/job-runs/${saveRun.body.id}`,'GET',undefined,user)).body.status==='completed','save retry');
  assert.equal(calls,beforeSave+1,'DB retry must not make a second provider request');
  await pool.query('DROP TRIGGER fail_save ON job_run_items');
  providerMode='permanent';const beforeError=calls;
  const failed=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await waitFor(async()=>(await request(`/api/job-runs/${failed.body.id}`,'GET',undefined,user)).body.status==='failed','permanent provider error');
  assert.equal(calls,beforeError+1);
  // The retry cause is committed before backoff and survives worker interruption.
  providerMode='retryable';const beforeInterruption=calls;
  const interrupted=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  let recordedFailure='';
  await waitFor(async()=>{
    const item=(await pool.query("SELECT attempts,error FROM job_run_items WHERE run_id=$1 AND sku='a'",[interrupted.body.id])).rows[0];
    if(item.attempts===1&&item.error?.includes('HTTP 503')){recordedFailure=item.error;return true;}return false;
  },'durable transient provider failure');
  await stopWorker();stopWorker=undefined;
  assert.equal(calls,beforeInterruption+1,'Stopping during retry backoff prevents another dispatch');
  assert.match(recordedFailure,/QA attempt 1:.*HTTP 503.*Temporary provider outage/);
  assert.match(recordedFailure,/\[redacted\]/);assert.doesNotMatch(recordedFailure,/test-secret-only|sk-private-test|private-header|\n/);
  const interruptedHistory=(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body;
  assert.equal(interruptedHistory.items[0].error,recordedFailure);
  await pool.query("UPDATE job_run_items SET attempts=3 WHERE run_id=$1 AND sku='a'",[interrupted.body.id]);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body.status==='failed','exhausted recovery retains the provider failure');
  assert.equal(calls,beforeInterruption+1,'An exhausted resumed item never dispatches another paid request');
  const retainedFailure=(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body.items[0].error;
  assert.ok(retainedFailure.includes(recordedFailure));assert.match(retainedFailure,/fresh run/i);
  assert.doesNotMatch(retainedFailure,/test-secret-only|sk-private-test|private-header/);
  providerMode='wait';const beforeCancel=calls;
  const cancelled=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(cancelled.status,202,JSON.stringify(cancelled.body));
  await waitFor(async()=>calls>beforeCancel,'inflight cancel');
  assert.equal((await request(`/api/job-runs/${cancelled.body.id}/cancel`,'POST',{},user)).status,200);
  await waitFor(async()=>(await request(`/api/job-runs/${cancelled.body.id}`,'GET',undefined,user)).body.status==='cancelled','cancelled');
  assert.equal(calls,beforeCancel+1,'Cancel prevents dispatching the next SKU');
  await stopWorker();stopWorker=undefined;
  // Neither a restart nor a future retry may reset a consumed budget or deadline.
  const exhausted=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await pool.query("UPDATE job_run_items SET attempts=3 WHERE run_id=$1 AND sku='a'",[exhausted.body.id]);
  const beforeExhaustion=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${exhausted.body.id}`,'GET',undefined,user)).body.status==='failed','exhausted attempts');
  assert.equal(calls,beforeExhaustion);
  const exhaustionError=(await request(`/api/job-runs/${exhausted.body.id}`,'GET',undefined,user)).body.items[0].error;
  assert.match(exhaustionError,/interrupted.*fresh run/i,'Without a saved cause, exhausted recovery explains interruption and a fresh rerun');
  await stopWorker();stopWorker=undefined;
  const expired=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await pool.query("UPDATE job_run_items SET started_at=now()-interval '6 minutes' WHERE run_id=$1 AND sku='a'",[expired.body.id]);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${expired.body.id}`,'GET',undefined,user)).body.status==='failed','expired item deadline');
  assert.equal(calls,beforeExhaustion);
  await stopWorker();stopWorker=undefined;
  // Conversion and QA retain their independent durable model snapshots.
  const productUrl='https://8.8.8.8/product?variant=42';
  assert.equal((await edit('b',{source:{sap:'Brand: TestBrand',url:productUrl},scraped_markdown:''})).status,200);
  const webRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  const snapshotConfig=(await pool.query('SELECT configuration FROM job_runs WHERE id=$1',[webRun.body.id])).rows[0].configuration;
  assert.ok(!('scrapperModelName' in snapshotConfig.settings));assert.ok(!('selectors' in snapshotConfig));
  assert.doesNotMatch(JSON.stringify(snapshotConfig),/test-secret-only|apiKey|sgai-.*-secret/);
  await request('/api/provider-settings','PUT',{...configured,modelName:'next/qa',scraperModelName:'next/scrape'},admin);
  providerMode='success';let offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${webRun.body.id}`,'GET',undefined,user)).body.status==='completed','snapshotted retrieval');
  await stopWorker();stopWorker=undefined;
  assert.deepEqual(providerRequests.slice(offset).map(payload=>payload.model),['deepseek/deepseek-v4.1-flash']);
  assert.equal(scrapeRequests.at(-1),productUrl);
  assert.equal(conversionRequests.at(-1).model,DEFAULT_SETTINGS.scraperModelName);
  assert.doesNotMatch(JSON.stringify(conversionRequests.at(-1)),/test-secret-only|SAP takes precedence/);
  const qaRequest=providerRequests[offset];
  assert.equal(qaRequest.reasoning_effort,'low');assert.equal(qaRequest.max_tokens,10000);
  assert.deepEqual(qaRequest.response_format,{type:'json_object'});assert.ok(qaRequest.messages[0].content.includes(mappingRules));
  assert.match(qaRequest.messages[0].content,/SAP takes precedence/);
  const qaData=JSON.parse(qaRequest.messages[1].content);
  assert.equal(qaData.attribute_set,'TestSet');assert.equal(qaData.source_sap,'Brand: TestBrand');assert.equal(qaData.source_url,productUrl);
  assert.match(qaData.scraped_markdown,/Retrieved product/);
  assert.deepEqual(qaData.uploaded_template,{sku:'b',attributes__brand:'TestBrand',attributes__bullet_point_7:'Extra supplied bullet',custom_optional:''},'QA receives every original upload field without source-only columns');
  const webHistory=(await request(`/api/job-runs/${webRun.body.id}`,'GET',undefined,user)).body;
  assert.match(webHistory.items[1].result.scraped_markdown,/Retrieved product/);
  assert.doesNotMatch(JSON.stringify(webHistory),/sgai-.*-secret|apiKey/);
  assert.equal(webHistory.items[1].error,null);assert.equal(webHistory.items[1].result.qa_result.qa_status,'pass');
  assert.deepEqual(webHistory.items[1].result.qa_result.source_notes,{sap_used:true,url_used:true,source_conflicts:[]});
  assert.match((await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='b').scraped_markdown,/variant=42/);
  // Old job snapshots still retrieve with the cloud without rewriting stored configuration.
  await pool.query("UPDATE sku_data SET scraped_markdown=NULL,scrape_status=NULL WHERE sku='b'");
  const legacyRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  await pool.query("UPDATE job_runs SET configuration=jsonb_set(configuration,'{settings}',(configuration->'settings')-'scrapperModelName'-'scraperModelName') WHERE id=$1",[legacyRun.body.id]);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${legacyRun.body.id}`,'GET',undefined,user)).body.status==='completed','legacy retrieval defaults');
  await stopWorker();stopWorker=undefined;
  assert.equal(providerRequests[offset].model,'next/qa');
  assert.equal(providerRequests.length-offset,1);
  assert.equal(scrapeRequests.at(-1),productUrl);
  assert.equal(conversionRequests.at(-1).model,DEFAULT_SETTINGS.scraperModelName);
  assert.doesNotMatch(JSON.stringify(conversionRequests.at(-1)),/test-secret-only|SAP takes precedence/);
  // Keep the actual retrieval failure when no other evidence exists; never spend QA tokens on it.
  await pool.query("UPDATE sku_data SET source=$1,scraped_markdown=NULL,scrape_status=NULL WHERE sku='b'",[JSON.stringify({url:productUrl})]);
  scrapeBlocked=true;
  const blockedRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${blockedRun.body.id}`,'GET',undefined,user)).body.status==='failed','blocked page retains its retrieval error');
  await stopWorker();stopWorker=undefined;scrapeBlocked=false;
  const blockedItem=(await request(`/api/job-runs/${blockedRun.body.id}`,'GET',undefined,user)).body.items.find((item:any)=>item.sku==='b');
  assert.match(blockedItem.error,/website blocked browser access/);
  assert.equal(blockedItem.result.scrape_status,'failed');
  assert.equal(providerRequests.length,offset,'No QA request without usable source evidence');
  // Failed conversion retains the existing SAP-only fallback without saving incomplete Markdown.
  await pool.query("UPDATE sku_data SET source=$1 WHERE sku='b'",[JSON.stringify({url:productUrl,sap:'Brand: TestBrand'})]);
  conversionFailed=true;
  const fallbackRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${fallbackRun.body.id}`,'GET',undefined,user)).body.status==='completed','conversion failure falls back to SAP');
  await stopWorker();stopWorker=undefined;conversionFailed=false;
  const fallbackInput=JSON.parse(providerRequests[offset].messages[1].content);
  assert.equal(fallbackInput.source_sap,'Brand: TestBrand');assert.ok(!fallbackInput.scraped_markdown);
  const fallbackRow=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='b');
  assert.equal(fallbackRow.scrape_status,'failed');assert.equal(fallbackRow.scraped_markdown,null);
  // Retrieval is committed before QA; later model failure or cancellation cannot erase it.
  await request('/api/catalog','POST',[{...sku('url-only'),source:{url:productUrl}}],user);
  assert.equal((await request('/api/jobs','POST',{id:'url-only-job',name:'URL-only job',skus:['url-only'],attribute_set:'TestSet'},user)).status,201);
  providerMode='permanent';
  const failureAfterScrape=await request('/api/jobs/url-only-job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${failureAfterScrape.body.id}`,'GET',undefined,user)).body.status==='failed','QA failure after committed scrape');
  await stopWorker();stopWorker=undefined;
  const savedEvidence=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='url-only');
  assert.match(savedEvidence.scraped_markdown,/Retrieved product/);assert.equal(savedEvidence.scrape_status,'success');
  assert.equal(savedEvidence.revision,1);assert.equal(savedEvidence.scrape_metadata.method,'cloud');
  const savedItem=(await pool.query('SELECT revision,snapshot FROM job_run_items WHERE run_id=$1',[failureAfterScrape.body.id])).rows[0];
  assert.equal(savedItem.revision,savedEvidence.revision);assert.equal(savedItem.snapshot.scraped_markdown,savedEvidence.scraped_markdown);
  const cancelUrl='https://8.8.8.8/new-product';
  await edit('url-only',{source:{url:cancelUrl}});
  providerMode='wait';const callsBeforeCancel=calls;
  const cancelAfterScrape=await request('/api/jobs/url-only-job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>calls>callsBeforeCancel,'QA started after fresh scrape');
  const beforeCancelEvidence=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='url-only');
  assert.equal(beforeCancelEvidence.scrape_metadata.requestedUrl,cancelUrl);
  assert.equal(beforeCancelEvidence.revision,3,'Source edit and new scrape each advance evidence revision');
  await request(`/api/job-runs/${cancelAfterScrape.body.id}/cancel`,'POST',{},user);
  await waitFor(async()=>(await request(`/api/job-runs/${cancelAfterScrape.body.id}`,'GET',undefined,user)).body.status==='cancelled','Cancellation after committed scrape');
  await stopWorker();stopWorker=undefined;
  assert.equal((await pool.query("SELECT scraped_markdown FROM sku_data WHERE sku='url-only'")).rows[0].scraped_markdown,beforeCancelEvidence.scraped_markdown);
  providerMode='success';
  // Imported legacy reviews are rerun; trusted skipped reviews have their own durable result.
  const forgedQa={qa_status:'warning',issues:[{field:'brand',suggested_fix:'Forged brand'}]};
  const legacyRaw={...sku('a').raw_row,qa_result:forgedQa};
  await pool.query("UPDATE sku_data SET raw_row=$1,qa_result=NULL,export_data=$2,status='completed',error=NULL WHERE sku='a'",[JSON.stringify(legacyRaw),JSON.stringify(forgedQa)]);
  const trustedB=history.items[1].result;
  await pool.query("UPDATE sku_data SET qa_result=$1,export_data=$2,qa_revision=revision,status='completed',error=NULL WHERE sku='b'",[JSON.stringify(trustedB.qa_result),JSON.stringify(trustedB.export_data)]);
  const unverified=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='a');
  assert.equal(unverified.status,'ready');assert.equal(unverified.qa_result,null);
  assert.equal(unverified.export_data,null);assert.equal(unverified.error,'Legacy review is unverified; rerun QA.');
  assert.ok(!Object.hasOwn(unverified.raw_row,'qa_result'));
  await edit('a',{source:sku('a').source});
  assert.equal((await pool.query("SELECT error FROM sku_data WHERE sku='a'")).rows[0].error,null,'Raw QA never triggers evidence-edit invalidation');
  const unfinished=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'unfinished'},user);
  assert.equal(unfinished.status,202);
  assert.equal(unfinished.body.items[0].status,'queued');
  assert.equal(unfinished.body.items[1].status,'skipped');
  assert.deepEqual(unfinished.body.items[1].result.qa_result,trustedB.qa_result);
  assert.ok(!Object.hasOwn(unfinished.body.items[1].snapshot,'qa_result'));
  const beforeLegacyCalls=calls;
  const beforeLegacyUsage=(await pool.query("SELECT tokens_used FROM jobs WHERE id='job'")).rows[0].tokens_used.total_tokens;
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${unfinished.body.id}`,'GET',undefined,user)).body.status==='completed','legacy review rerun');
  await stopWorker();stopWorker=undefined;
  assert.equal(calls,beforeLegacyCalls+1,'Only the unverified review is sent to the mocked provider');
  const reviewed=(await request(`/api/job-runs/${unfinished.body.id}`,'GET',undefined,user)).body;
  assert.equal(reviewed.items[0].result.qa_result.qa_status,'pass');
  assert.deepEqual(reviewed.items[1].result.qa_result,trustedB.qa_result);
  const savedLegacy=(await pool.query("SELECT raw_row,qa_result FROM sku_data WHERE sku='a'")).rows[0];
  assert.deepEqual(savedLegacy.raw_row,legacyRaw,'Reruns preserve original stored legacy data');
  assert.equal(savedLegacy.qa_result.qa_status,'pass');
  const afterLegacyJob=(await pool.query("SELECT status,tokens_used FROM jobs WHERE id='job'")).rows[0];
  assert.equal(afterLegacyJob.status,'completed');
  assert.equal(afterLegacyJob.tokens_used.total_tokens,beforeLegacyUsage+15,'Skipped prior reviews do not charge usage twice');
  assert.ok(!Object.hasOwn((await pool.query("SELECT raw_row FROM sku_data WHERE sku='b'")).rows[0].raw_row,'qa_result'),'New worker reviews are never mirrored into raw rows');
  await edit('a',{source:{sap:'Changed after genuine review'}});
  const staleReview=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='a');
  assert.equal(staleReview.qa_stale,true);assert.equal(staleReview.qa_result,null);assert.equal(staleReview.export_data,null);
  assert.ok((await pool.query("SELECT qa_result FROM sku_data WHERE sku='a'")).rows[0].qa_result,'Invalidation preserves the stored genuine prior review');
  assert.deepEqual((await request(`/api/job-runs/${unfinished.body.id}`,'GET',undefined,user)).body.items[0].result,reviewed.items[0].result,'Genuine history survives later catalog edits');
  // An older skipped snapshot, even with top-level QA, is evidence only.
  const snapshotOnly=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  const oldSnapshot={...trustedB,raw_row:{...trustedB.raw_row,qa_result:forgedQa}};
  await pool.query("UPDATE job_run_items SET snapshot=$2,result=NULL WHERE run_id=$1 AND sku='b'",[snapshotOnly.body.id,JSON.stringify(oldSnapshot)]);
  const oldItem=(await request(`/api/job-runs/${snapshotOnly.body.id}`,'GET',undefined,user)).body.items[1];
  assert.equal(oldItem.result,null);assert.equal(oldItem.snapshot.status,'ready');
  assert.equal(oldItem.snapshot.error,'Legacy review is unverified; rerun QA.');
  for(const key of ['qa_result','export_data','tokensUsed','timeTaken','last_job_id'])assert.ok(!Object.hasOwn(oldItem.snapshot,key));
  assert.ok(!Object.hasOwn(oldItem.snapshot.raw_row,'qa_result'));
  assert.deepEqual((await pool.query("SELECT snapshot FROM job_run_items WHERE run_id=$1 AND sku='b'",[snapshotOnly.body.id])).rows[0].snapshot,oldSnapshot,'Reading history never rewrites legacy snapshots');
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${snapshotOnly.body.id}`,'GET',undefined,user)).body.status==='completed','snapshot-only history completion');
  await stopWorker();stopWorker=undefined;
  assert.equal((await pool.query("SELECT status FROM jobs WHERE id='job'")).rows[0].status,'pending','Unverified skipped snapshots cannot complete a job');

  // Catalog jobs use independent results and the mapping snapshotted at admission.
  const catalogUpload={...sku('mandatory-catalog-input'),raw_row:{...Object.fromEntries(CATALOG_INPUT_HEADERS.map(header=>[header,''])),
    sku:'mandatory-catalog-input',base_code:'00001',attributes__lulu_ean:'0001234567890',attributes__sap:'Brand: Canonical',
    attributes__url:'https://example.com/canonical',attributes__attribute_set:'TestSet',attribute__shipping_attribute:'001'},
    source:{sap:'Wrong context',url:'https://example.com/wrong'},attribute_set:'Wrong category'};
  const incompleteUpload={...catalogUpload,sku:'missing-catalog-header',raw_row:{...catalogUpload.raw_row}};
  delete (incompleteUpload.raw_row as Record<string,unknown>).base_code;
  assert.equal((await request('/api/catalog?mode=catalog','POST',[catalogUpload,incompleteUpload],user)).status,400);
  assert.equal((await pool.query("SELECT 1 FROM sku_data WHERE sku=ANY($1)",[['mandatory-catalog-input','missing-catalog-header']])).rows.length,0,'Invalid catalog headers reject the whole batch');
  assert.equal((await request('/api/catalog?mode=catalog','POST',[catalogUpload],user)).status,200);
  assert.deepEqual((await pool.query("SELECT raw_row FROM sku_data WHERE sku='mandatory-catalog-input'")).rows[0].raw_row,catalogUpload.raw_row,'Catalog uploads retain supplied text and blank cells');
  const canonicalUpload=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='mandatory-catalog-input');
  assert.equal(canonicalUpload.source.sap,'Brand: Canonical');assert.equal(canonicalUpload.source.url,'https://example.com/canonical');
  assert.equal(canonicalUpload.attribute_set,'TestSet','Canonical category comes from the required uploaded column');
  const catalogHeaders=['sku','base_code','attribute_set','attributes__lulu_ean','attributes__Shipping_Attribute',
    'attributes__Shipment_Type','attributes__Common_Item_Whippy','attributes__fallback','name','attributes__color',
    'attributes__shipping_weight','attributes__brand','attributes__lulu_product_type'];
  const catalogRules='name: use the sourced brand and model, for example TestBrand USB Hub.\nattributes__fallback: default No. Leave unsourced color blank.';
  const catSku=(id:string)=>({...sku(id),raw_row:{sku:id,base_code:'00001',attributes__lulu_ean:'0001234567890',attributes__region:'UAE'},
    upload_attributes:{lulu_ean:'0001234567890',Shipping_Attribute:'001',Shipment_Type:'Normal',Common_Item_Whippy:'No'}});
  const legacyCatSku={...catSku('cat-a'),raw_row:{...catSku('cat-a').raw_row,attributes__product_type:' 000Legacy Hub '}};
  assert.equal((await request('/api/catalog','POST',[legacyCatSku,catSku('cat-b')],user)).status,200);
  const catalogJob={id:'catalog-job',name:'Catalog',skus:['cat-a','cat-b'],attribute_set:'TestSet',jobType:'catalog'};
  assert.equal((await request('/api/jobs','POST',catalogJob,user)).status,400,'Catalog jobs require separately configured output headers');
  assert.equal((await request('/api/jobs','POST',{...catalogJob,jobType:'unknown'},user)).status,400);
  const saveCatalogRules=async(rules:string,headers?:string[])=>request(`/api/attribute-sets/${testSet.id}`,'PUT',
    {name:'TestSet',rulesMarkdown:rules,...(headers!==undefined?{catalogHeaders:headers}:{})},admin);
  assert.equal((await request(`/api/attribute-sets/${testSet.id}`,'PUT',{name:'TestSet',rulesMarkdown:catalogRules,catalogHeaders},user)).status,403,'Output-header edits keep administrator permissions');
  await saveCatalogRules(catalogRules,catalogHeaders);
  assert.equal((await request('/api/jobs','POST',catalogJob,user)).body[0].jobType,'catalog');
  assert.equal((await request('/api/jobs/catalog-job','PUT',{jobType:'qa'},user)).status,400,'Job types are immutable');
  assert.equal((await request('/api/catalog','POST',[{...catSku('forged-catalog'),catalog_state:{status:'completed'}}],user)).status,400);
  await pool.query("UPDATE sku_data SET status='completed',qa_result=$1,qa_revision=revision,export_data=$1,tokens_used=$2 WHERE sku='cat-a'",
    [JSON.stringify(trustedB.qa_result),JSON.stringify({prompt_tokens:10,completion_tokens:5,total_tokens:15})]);
  const unchangedQa=async()=> (await pool.query("SELECT sku,raw_row,upload_attributes,status,qa_result,qa_revision,export_data,tokens_used,time_taken,error,last_job_id FROM sku_data WHERE sku=ANY($1) ORDER BY sku",[['cat-a','cat-b']])).rows;
  const beforeCatalog=await unchangedQa();
  const startCatalog=(mode='unfinished',selectedSku?:string,id='catalog-job')=>request(`/api/jobs/${id}/runs`,'POST',
    {requestId:randomUUID(),mode,...(selectedSku?{sku:selectedSku}:{})},user);
  assert.equal((await request('/api/provider-settings','PUT',configured,admin)).status,200);
  const firstCatalog=await startCatalog();assert.equal(firstCatalog.status,202);
  assert.equal(firstCatalog.body.jobType,'catalog');assert.deepEqual(firstCatalog.body.catalogHeaders,catalogHeaders);
  await saveCatalogRules(catalogRules.replace('USB Hub','Changed Mapping Example'),[...catalogHeaders].reverse());
  const catalogOffset=providerRequests.length;
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  const catalogRun=async(id:string)=>(await request(`/api/job-runs/${id}`,'GET',undefined,user)).body;
  await waitFor(async()=>(await catalogRun(firstCatalog.body.id)).status==='completed','catalog generation');
  await stopWorker();stopWorker=undefined;
  const generatedCatalog=await catalogRun(firstCatalog.body.id);
  assert.deepEqual(generatedCatalog.catalogHeaders,catalogHeaders,'Header edits do not change admitted runs');
  assert.ok(providerRequests[catalogOffset].messages[0].content.includes(catalogRules),'Mapping updates do not change admitted runs');
  assert.deepEqual(await unchangedQa(),beforeCatalog,'Catalog commits never overwrite QA state or original upload data');
  assert.equal((await pool.query("SELECT status FROM jobs WHERE id='catalog-job'")).rows[0].status,'completed');
  assert.ok(providerRequests.slice(catalogOffset).every(payload=>payload.reasoning_effort==='none'),'DeepSeek Catalog disables thinking while QA retains low effort');
  for(const item of generatedCatalog.items) {
    assert.equal(item.result.catalog_state.row.attributes__lulu_ean,'0001234567890');
    assert.equal(item.result.catalog_state.row.attributes__Shipping_Attribute,'001');
    assert.equal(item.result.catalog_state.row.base_code,'00001');
    assert.equal(item.result.catalog_state.row.attributes__fallback,'No');
    assert.equal(item.result.catalog_state.row.attributes__color,'');
    assert.equal(item.result.catalog_state.row.sku,item.sku);
    for(const header of ['attributes__shipping_weight','attributes__brand']) assert.equal(item.result.catalog_state.row[header],'','Blank pass-through values remain blank despite model changes');
    assert.equal(item.result.catalog_state.row.attributes__lulu_product_type,item.sku==='cat-a'?' 000Legacy Hub ':'','Renamed product types preserve legacy values and blanks despite model changes');
    assert.ok(item.result.catalog_state.warnings.some((warning:string)=>warning.includes('attributes__color')));
    assert.ok(item.result.catalog_state.cellWarnings.some((warning:any)=>warning.header==='attributes__color'));
    assert.ok(item.result.catalog_state.cellWarnings.some((warning:any)=>warning.header==='name'&&warning.message.includes('SAP')));
    assert.equal(item.result.qa_result,undefined);
  }
  await saveCatalogRules(catalogRules,catalogHeaders);
  const skippedCatalog=await startCatalog();assert.ok(skippedCatalog.body.items.every((item:any)=>item.status==='skipped'));
  const skippedCalls=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(skippedCatalog.body.id)).status==='completed','catalog completed-row reuse');
  await stopWorker();stopWorker=undefined;assert.equal(calls,skippedCalls);
  assert.equal((await pool.query("SELECT tokens_used FROM jobs WHERE id='catalog-job'")).rows[0].tokens_used.total_tokens,30,'Skipped results are not charged again');
  await pool.query("UPDATE job_run_items SET result=jsonb_set(result,'{catalog_state,row,attributes__brand}',$2::jsonb) WHERE run_id=$1 AND sku='cat-a'",
    [skippedCatalog.body.id,JSON.stringify('Legacy generated brand')]);
  const legacyPassThrough=await startCatalog();assert.deepEqual(legacyPassThrough.body.items.map((item:any)=>item.status),['queued','skipped'],'Older rows that changed pass-through values must be regenerated');
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(legacyPassThrough.body.id)).status==='completed','catalog legacy pass-through correction');
  await stopWorker();stopWorker=undefined;
  await pool.query("UPDATE job_run_items SET result=result #- '{catalog_state,cellWarnings}' WHERE run_id=$1 AND sku='cat-a'",[legacyPassThrough.body.id]);
  const legacyCellFindings=await startCatalog();
  assert.deepEqual(legacyCellFindings.body.items.map((item:any)=>item.status),['queued','skipped'],'Rows without structured cell findings regenerate once');
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(legacyCellFindings.body.id)).status==='completed','catalog legacy cell findings regeneration');
  await stopWorker();stopWorker=undefined;
  assert.ok(Array.isArray((await catalogRun(legacyCellFindings.body.id)).items[0].result.catalog_state.cellWarnings));
  assert.equal((await catalogRun(legacyPassThrough.body.id)).items[0].result.catalog_state.cellWarnings,undefined,'Legacy history stays readable and unchanged');
  await saveCatalogRules(catalogRules,[...catalogHeaders].reverse());
  const reorderedCatalog=await startCatalog();assert.ok(reorderedCatalog.body.items.every((item:any)=>item.status==='queued'),'Header-only changes invalidate completed result reuse');
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(reorderedCatalog.body.id)).status==='completed','catalog reordered header generation');
  await stopWorker();stopWorker=undefined;
  assert.deepEqual((await catalogRun(reorderedCatalog.body.id)).catalogHeaders,[...catalogHeaders].reverse());
  assert.deepEqual((await catalogRun(firstCatalog.body.id)).catalogHeaders,catalogHeaders,'Historical exports retain original header order');
  await saveCatalogRules(catalogRules,catalogHeaders);
  providerMode='catalog-mixed';const mixedCatalog=await startCatalog('all');stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(mixedCatalog.body.id)).status==='failed','catalog invalid response');
  await stopWorker();stopWorker=undefined;
  assert.equal((await catalogRun(mixedCatalog.body.id)).items[1].result.catalog_state.status,'failed');
  assert.equal((await catalogRun(mixedCatalog.body.id)).items[1].result.catalog_state.tokensUsed.total_tokens,15,'Invalid generated answers still record provider usage');
  const resumeCatalog=await startCatalog();assert.deepEqual(resumeCatalog.body.items.map((item:any)=>item.status),['skipped','queued']);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(resumeCatalog.body.id)).status==='completed','catalog failed-row retry');
  await stopWorker();stopWorker=undefined;

  // New catalog jobs cannot reuse another job's mirror. Cancellation keeps committed rows.
  assert.equal((await request('/api/jobs','POST',{...catalogJob,id:'catalog-other'},user)).status,201);
  const freshCatalog=await startCatalog('unfinished',undefined,'catalog-other');
  assert.ok(freshCatalog.body.items.every((item:any)=>item.status==='queued'));
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(freshCatalog.body.id)).status==='completed','independent catalog job execution');
  await stopWorker();stopWorker=undefined;
  const otherCatalog=await startCatalog('all',undefined,'catalog-other');
  providerMode='wait';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>{
    const detail=await catalogRun(otherCatalog.body.id);
    return detail.items[0].status==='completed' && detail.items[1].attempts===1;
  },'catalog partial completion before cancellation');
  assert.equal((await request(`/api/job-runs/${otherCatalog.body.id}/cancel`,'POST',{},user)).status,200);
  await waitFor(async()=>(await catalogRun(otherCatalog.body.id)).status==='cancelled','catalog cancellation');
  await stopWorker();stopWorker=undefined;
  assert.equal((await catalogRun(otherCatalog.body.id)).items[0].result.catalog_state.status,'completed');
  const afterCancel=await startCatalog('unfinished',undefined,'catalog-other');
  assert.deepEqual(afterCancel.body.items.map((item:any)=>item.status),['skipped','queued']);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(afterCancel.body.id)).status==='completed','catalog resume after cancellation');
  await stopWorker();stopWorker=undefined;

  // New evidence fences the live mirror while preserving the old run's export.
  providerMode='wait';const driftCatalog=await startCatalog('single','cat-a');const driftOffset=providerRequests.length;
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>providerRequests.length>driftOffset,'catalog in-flight evidence edit');
  await edit('cat-a',{source:{sap:'Brand: TestBrand; updated product facts'}});
  await waitFor(async()=>(await catalogRun(driftCatalog.body.id)).status==='completed','catalog historical result save');
  await stopWorker();stopWorker=undefined;
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.find((item:any)=>item.sku==='cat-a').catalog_state,null);
  assert.equal((await catalogRun(driftCatalog.body.id)).items[0].result.catalog_state.revision,0);
  await saveCatalogRules(catalogRules.replace('USB Hub','Changed Mapping Example'));
  const changedMapping=await startCatalog();assert.ok(changedMapping.body.items.every((item:any)=>item.status==='queued'),'Changed mappings invalidate reuse');
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(changedMapping.body.id)).status==='completed','catalog changed mapping regeneration');
  await stopWorker();stopWorker=undefined;

  // Grouped jobs prepare files without model calls, then retain each set's own run schema.
  await saveCatalogRules(catalogRules,catalogHeaders);
  const hubHeaders=[...catalogHeaders].reverse().concat('attributes__description');
  const hubSet=(await request('/api/attribute-sets','POST',{name:'Hub',rulesMarkdown:catalogRules,catalogHeaders:hubHeaders},admin)).body;
  const shippingSku=(id:string,set:string,region='UAE')=>({...sku(id),attribute_set:set,
    raw_row:{...Object.fromEntries(CATALOG_INPUT_HEADERS.map(header=>[header,''])),sku:id,base_code:'00003',
      attributes__lulu_ean:'0001234567893',attributes__sap:'Brand: TestBrand',attributes__url:'',attributes__attribute_set:set,
      attributes__region:region,attribute__shipping_attribute:' 003 ',attribute__shipment_type:'Express',
      attribute__common_item_whippy:'0007',attribute__fallback:''}});
  const multiA=shippingSku('multi-a','TestSet',' uae '),multiB=shippingSku('multi-b','Hub'),multiC=shippingSku('multi-c','TestSet');
  multiC.raw_row.attributes__sap='';multiC.raw_row.attributes__url='https://8.8.8.8/grouped-url-only';
  assert.equal((await request('/api/catalog?mode=catalog','POST',[multiA,multiB,multiC,shippingSku('multi-qtr','Hub','QTR'),shippingSku('multi-missing','Hub','')],user)).status,200);
  const multiJob={id:'multi-job',name:'Multiple sets',skus:['multi-b','multi-c','multi-a'],jobType:'catalog'};
  assert.equal((await request('/api/jobs','POST',{...multiJob,skus:['multi-a','multi-qtr']},user)).status,400);
  assert.equal((await request('/api/jobs','POST',{...multiJob,skus:['multi-missing']},user)).status,400);
  await request(`/api/attribute-sets/${hubSet.id}`,'PUT',{name:'Hub',rulesMarkdown:catalogRules,catalogHeaders:[]},admin);
  const missingGroup=await request('/api/jobs','POST',multiJob,user);assert.equal(missingGroup.status,400);assert.match(missingGroup.body.error,/Hub:.*Catalog Output Headers/);
  assert.equal((await pool.query("SELECT 1 FROM jobs WHERE id='multi-job'")).rowCount,0,'Every set is validated before saving any job files');
  await request(`/api/attribute-sets/${hubSet.id}`,'PUT',{name:'Hub',rulesMarkdown:catalogRules,catalogHeaders:hubHeaders},admin);
  for(const key of ['catalog_outputs','catalogOutputs','attributeSets']) assert.equal((await request('/api/jobs','POST',{...multiJob,[key]:{}},user)).status,400);
  const beforeFilesCalls=calls,beforeFilesScrapes=scrapeRequests.length;
  const createdMulti=await request('/api/jobs','POST',multiJob,user);assert.equal(createdMulti.status,201);
  assert.equal(calls,beforeFilesCalls);assert.equal(scrapeRequests.length,beforeFilesScrapes);
  assert.deepEqual(createdMulti.body[0].attributeSets,['Hub','TestSet']);assert.equal(createdMulti.body[0].attribute_set,'');
  assert.ok(!('catalog_outputs' in createdMulti.body[0]));
  assert.equal((await request('/api/jobs/multi-job/outputs')).status,401);
  assert.equal((await request('/api/jobs/job/outputs','GET',undefined,user)).status,400);
  assert.equal((await request('/api/jobs/no-such-job/outputs','GET',undefined,user)).status,404);
  const preparedMulti=(await request('/api/jobs/multi-job/outputs','GET',undefined,user)).body;
  assert.deepEqual(preparedMulti.groups.map((group:any)=>group.headers),[hubHeaders,catalogHeaders]);
  assert.deepEqual(preparedMulti.groups[1].rows.map((row:any)=>row.sku),['multi-c','multi-a']);
  assert.equal(preparedMulti.groups[0].rows[0].name,'');
  assert.deepEqual(preparedMulti.shipping.rows.map((row:any)=>row.sku),multiJob.skus);
  assert.equal(preparedMulti.shipping.headers.length,16);assert.equal(preparedMulti.shipping.rows[0].attributes__erp_shipping_attribute,' 003 ');
  assert.equal(preparedMulti.shipping.rows[0].attributes__erp_shipping_attribute_qtr,'Courier delivery');
  assert.equal(preparedMulti.shipping.rows[0].attributes__common_item_whippy_uae,'0007');
  assert.equal(preparedMulti.shipping.rows[0].fallback_uae,'');
  assert.equal((await request('/api/jobs/multi-job','PUT',{catalogOutputs:{}},user)).status,400);
  const editMulti=await request('/api/jobs/multi-job','PUT',{skus:['multi-a','multi-b']},user);assert.equal(editMulti.status,200);
  assert.deepEqual((await request('/api/jobs/multi-job/outputs','GET',undefined,user)).body.shipping.rows.map((row:any)=>row.sku),['multi-a','multi-b']);
  const rejectedMembership=await request('/api/jobs/multi-job','PUT',{skus:['multi-a','multi-qtr']},user);assert.equal(rejectedMembership.status,400);
  assert.deepEqual((await request('/api/jobs/multi-job/outputs','GET',undefined,user)).body.shipping.rows.map((row:any)=>row.sku),['multi-a','multi-b'],'Invalid membership edits retain the saved files');
  assert.equal((await request('/api/jobs/multi-job','PUT',{skus:multiJob.skus},user)).status,200);
  const multiRun=await startCatalog('unfinished',undefined,'multi-job');assert.equal(multiRun.status,202);
  assert.deepEqual(multiRun.body.catalogGroups.map((group:any)=>group.attributeSet),['Hub','TestSet']);
  await request(`/api/attribute-sets/${hubSet.id}`,'PUT',{name:'Hub',rulesMarkdown:catalogRules,catalogHeaders:[...hubHeaders].reverse()},admin);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(multiRun.body.id)).status==='completed','grouped Catalog generation');
  await stopWorker();stopWorker=undefined;
  const generatedMulti=await catalogRun(multiRun.body.id);
  assert.deepEqual(generatedMulti.items[0].result.catalog_state.headers,hubHeaders,'Running groups keep their admitted headers');
  assert.deepEqual(generatedMulti.items[1].result.catalog_state.headers,catalogHeaders);
  assert.equal(generatedMulti.catalogOutputs.shipping.rows.length,3);
  const changedGroup=await startCatalog('unfinished',undefined,'multi-job');assert.equal(changedGroup.status,202);
  assert.deepEqual(changedGroup.body.items.map((item:any)=>item.status),['queued','skipped','skipped'],'Only a changed group is regenerated');
  assert.deepEqual(changedGroup.body.catalogOutputs.groups[0].headers,[...hubHeaders].reverse());
  assert.deepEqual((await request('/api/jobs/multi-job/outputs','GET',undefined,user)).body.groups[0].headers,[...hubHeaders].reverse());
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(changedGroup.body.id)).status==='completed','changed group resume');
  await stopWorker();stopWorker=undefined;
  assert.deepEqual((await catalogRun(multiRun.body.id)).catalogOutputs,generatedMulti.catalogOutputs,'Historical files never follow live mapping edits');
  await initializeDatabase(pool);
  assert.deepEqual((await request('/api/jobs/multi-job/outputs','GET',undefined,user)).body.shipping,preparedMulti.shipping,'Prepared shipping survives migrations');

  await request(`/api/attribute-sets/${hubSet.id}`,'PUT',{name:'Hub',rulesMarkdown:catalogRules+' Changed rule.'},admin);
  const groupRules=await startCatalog('unfinished',undefined,'multi-job');
  assert.deepEqual(groupRules.body.items.map((item:any)=>item.status),['queued','skipped','skipped'],'Rules-only changes invalidate their own group');
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(groupRules.body.id)).status==='completed','group rules-only resume');
  await stopWorker();stopWorker=undefined;
  providerMode='catalog-mixed';const groupFailure=await startCatalog('all',undefined,'multi-job');
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(groupFailure.body.id)).status==='failed','group failed-row handling');
  await stopWorker();stopWorker=undefined;
  const failedGroups=await catalogRun(groupFailure.body.id);
  assert.deepEqual(failedGroups.items.map((item:any)=>item.status),['failed','completed','completed']);
  assert.equal(failedGroups.catalogOutputs.shipping.rows.length,3,'Shipping retains failed Catalog SKUs');
  const groupRetry=await startCatalog('unfinished',undefined,'multi-job');
  assert.deepEqual(groupRetry.body.items.map((item:any)=>item.status),['queued','skipped','skipped']);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(groupRetry.body.id)).status==='completed','group failed-row retry');
  await stopWorker();stopWorker=undefined;
  providerMode='wait';const groupCancel=await startCatalog('all',undefined,'multi-job');stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>{ const run=await catalogRun(groupCancel.body.id);return run.items[0].status==='completed' && run.items[1].attempts===1; },'group partial completion');
  assert.equal((await request(`/api/job-runs/${groupCancel.body.id}/cancel`,'POST',{},user)).status,200);
  await waitFor(async()=>(await catalogRun(groupCancel.body.id)).status==='cancelled','group cancellation');
  await stopWorker();stopWorker=undefined;
  assert.equal((await catalogRun(groupCancel.body.id)).items[0].result.catalog_state.status,'completed');
  assert.equal((await catalogRun(groupCancel.body.id)).catalogOutputs.shipping.rows.length,3);
  const groupResume=await startCatalog('unfinished',undefined,'multi-job');
  assert.deepEqual(groupResume.body.items.map((item:any)=>item.status),['skipped','queued','queued']);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(groupResume.body.id)).status==='completed','group cancelled-row resume');
  await stopWorker();stopWorker=undefined;

  const phoneHeaders=[...catalogHeaders,'attributes__capacity'];
  assert.equal((await request('/api/attribute-sets','POST',{name:'Phone',rulesMarkdown:catalogRules,catalogHeaders:phoneHeaders},admin)).status,201);
  assert.equal((await request('/api/catalog?mode=catalog','POST',[shippingSku('three-tv','TestSet'),shippingSku('three-hub','Hub'),shippingSku('three-phone','Phone')],user)).status,200);
  const beforeThreeCalls=calls,beforeThreeScrapes=scrapeRequests.length;
  const threeJob={id:'three-category-job',name:'Three categories',jobType:'catalog',skus:['three-tv','three-hub','three-phone']};
  assert.equal((await request('/api/jobs','POST',threeJob,user)).status,201);
  assert.equal(calls,beforeThreeCalls);assert.equal(scrapeRequests.length,beforeThreeScrapes,'Creation makes no paid requests');
  const threePrepared=(await request('/api/jobs/three-category-job/outputs','GET',undefined,user)).body;
  assert.equal(threePrepared.groups.length,3);
  assert.deepEqual(threePrepared.groups.map((group:any)=>group.rows.map((row:any)=>row.sku)),[['three-tv'],['three-hub'],['three-phone']]);
  assert.deepEqual(threePrepared.shipping.rows.map((row:any)=>row.sku),threeJob.skus);
  assert.equal(threePrepared.shipping.headers.length,16);
  const threeRun=await startCatalog('all',undefined,threeJob.id);assert.equal(threeRun.status,202);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(threeRun.body.id)).status==='completed','three-category parent execution');
  await stopWorker();stopWorker=undefined;
  const threeCompleted=await catalogRun(threeRun.body.id);
  assert.equal(threeCompleted.catalogGroups.length,3);
  assert.equal(threeCompleted.items.filter((item:any)=>item.result.catalog_state.status==='completed').length,3);
  assert.deepEqual(threeCompleted.items[2].result.catalog_state.headers,phoneHeaders);
  assert.equal(threeCompleted.catalogOutputs.shipping.rows.length,3);
  assert.ok(threeCompleted.items.every((item:any)=>Array.isArray(item.result.catalog_state.cellWarnings)));
  assert.equal((await request('/api/provider-settings','PUT',{...configured,modelName:'custom/catalog'},admin)).status,200);
  const customCatalogOffset=providerRequests.length;
  const customCatalogRun=await startCatalog('single','three-phone',threeJob.id);assert.equal(customCatalogRun.status,202);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(customCatalogRun.body.id)).status==='completed','custom Catalog model execution');
  await stopWorker();stopWorker=undefined;
  assert.equal(providerRequests[customCatalogOffset].model,'custom/catalog');
  assert.equal(providerRequests[customCatalogOffset].reasoning_effort,undefined,'Custom models receive no DeepSeek-specific reasoning option');
  assert.equal((await request('/api/provider-settings','PUT',configured,admin)).status,200);
  assert.equal((await request('/api/jobs/three-category-job','DELETE',undefined,admin)).status,200);

  // Legacy regionless and mixed-region definitions can still generate Catalog files.
  await pool.query("INSERT INTO jobs(id,name,created_at,job_type,attribute_set,skus) VALUES('legacy-shipping','Legacy', $1,'catalog','Hub',$2)",[new Date().toISOString(),JSON.stringify(['multi-missing','multi-qtr'])]);
  const legacyShipping=await startCatalog('unfinished',undefined,'legacy-shipping');assert.equal(legacyShipping.status,202);
  assert.equal(legacyShipping.body.catalogOutputs.shipping,null);assert.match(legacyShipping.body.catalogOutputs.shippingError,/unavailable/);
  // Simulate the saved singleton configuration of a run admitted before this upgrade.
  await pool.query("UPDATE job_runs SET configuration=configuration-'catalogMappings'-'catalogOutputs' WHERE id=$1",[legacyShipping.body.id]);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await catalogRun(legacyShipping.body.id)).status==='completed','legacy shipping-unavailable run');
  await stopWorker();stopWorker=undefined;
  assert.equal((await catalogRun(legacyShipping.body.id)).catalogOutputs.shipping,null);
  assert.equal((await request('/api/jobs/multi-job','DELETE',undefined,admin)).status,200);
  assert.equal((await request('/api/jobs/legacy-shipping','DELETE',undefined,admin)).status,200);
  await saveCatalogRules('');
  assert.equal((await startCatalog()).status,400,'Existing catalog jobs require nonempty mapping rules at every run');
  await saveCatalogRules(catalogRules,[]);
  assert.equal((await startCatalog()).status,400,'Existing catalog jobs require configured output headers at every run');
  for(const id of ['catalog-job','catalog-other']) assert.equal((await request(`/api/jobs/${id}`,'DELETE',undefined,admin)).status,200);

  await initializeDatabase(pool); // Existing populated records remain readable after restart migrations.
  // Clear remains all-or-nothing even if catalog deletion fails after deleting jobs.
  await pool.query("CREATE FUNCTION fail_clear() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected clear failure'; END $$; CREATE TRIGGER fail_clear BEFORE DELETE ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_clear()");
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,503);
  assert.deepEqual((await request('/api/jobs','GET',undefined,user)).body.map((job:any)=>job.id).sort(),['job','url-only-job']);
  await pool.query('DROP TRIGGER fail_clear ON sku_data');
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,200);
  assert.equal((await request('/api/jobs','GET',undefined,user)).body.length,0);
  await request('/api/users/user','PUT',{password:'replacement-test-password'},admin);
  assert.equal((await request('/api/catalog','GET',undefined,user)).status,401);
  await pool.query('UPDATE sessions SET expires_at=now()-interval \'1 second\' WHERE token_hash=$1',[hashSessionToken(other.split('=')[1])]);
  assert.equal((await request('/api/catalog','GET',undefined,other)).status,401);
  await request('/api/auth/logout','POST',undefined,admin);
  assert.equal((await request('/api/catalog','GET',undefined,admin)).status,401);
  // Retired selector data never blocks startup and is left untouched.
  await pool.query("CREATE TABLE site_selectors(id text PRIMARY KEY,website text,selectors text); INSERT INTO site_selectors VALUES('one','Example.com','main'),('two','www.example.com','article')");
  await initializeDatabase(pool);await verifySchema(pool);
  assert.equal((await pool.query('SELECT * FROM site_selectors')).rowCount,2);
  assert.equal((await pool.query("SELECT website FROM site_selectors WHERE id='one'")).rows[0].website,'Example.com');
  console.log('Security/database checks passed: sessions, roles, atomic saves, recovery, ownership, cancellation, budgets, model snapshots, retrieval, catalog generation/resume/isolation, and preserved legacy data.');
} finally {
  await stopWorker?.();await stopSecond?.();server.closeAllConnections();provider.closeAllConnections();
  await Promise.all([new Promise<void>(resolve=>server.close(()=>resolve())),new Promise<void>(resolve=>provider.close(()=>resolve()))]);
  await pool.end();await root.query(`DROP SCHEMA ${namespace} CASCADE`);await root.end();
}
