import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import express from 'express';
import {Pool} from 'pg';
import {drizzle} from 'drizzle-orm/node-postgres';
import * as schema from '../db/schema';
import {initializeQaConfiguration,registerQaConfigurationRoutes} from '../db/qaConfiguration';
import {initializeDatabase,verifySchema} from './database';
import {initializeAuth,registerAuth,hashPassword,hashSessionToken} from './auth';
import {initializeProvider,registerProviderRoutes} from './provider';
import {initializeJobRuns,registerJobRunRoutes,startJobWorker} from './jobRunner';
import {ApiError,registerCatalogRoutes} from './catalog';
import {ProviderError} from '../lib/chatCompletion';
import {validateScrapeInput, ScrapeError, type ScrapeConfiguration} from '../lib/scrapeAgent';
import {DEFAULT_SCRAPE_SETTINGS} from '../lib/scrapeRequest';
import {DEFAULT_SETTINGS,editableSettings} from '../lib/providerSettings';

assert.ok(process.env.TEST_DATABASE_URL,'Set TEST_DATABASE_URL to a disposable PostgreSQL instance. Production DATABASE_URL is never used.');
const namespace=`security_${randomUUID().replaceAll('-','')}`;
const root=new Pool({connectionString:process.env.TEST_DATABASE_URL});
await root.query(`CREATE SCHEMA ${namespace}`);
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${namespace}`,max:10,query_timeout:5000});
const server=createServer();
let stopWorker:(()=>Promise<void>)|undefined;
let stopSecond:(()=>Promise<void>)|undefined;
let calls=0, providerMode='success';
const providerRequests:any[]=[];
const scrapeRequests:string[]=[];
const scrapeConfigurations:ScrapeConfiguration[]=[];
let scrapeBlocked=false;
const scrape=async(rawUrl:string, signal:AbortSignal, configuration:ScrapeConfiguration)=>{
  if(!configuration.apiKey)throw new ScrapeError('Save your ScrapeGraph API key in Scrapper agent.',503,'API_KEY_REQUIRED');
  const {url}=validateScrapeInput({url:rawUrl});signal.throwIfAborted();scrapeRequests.push(url);
  scrapeConfigurations.push(configuration);
  if(scrapeBlocked)throw new ScrapeError('The website blocked browser access.',502,'PAGE_BLOCKED');
  return '# Retrieved product\nBrand: TestBrand\n\nSource: <'+url+'>';
};
const provider=createServer(async(req,res)=>{
  let raw='';for await(const chunk of req) raw+=chunk;
  const payload=JSON.parse(raw);providerRequests.push(payload);
  calls++;
  if(providerMode==='wait') await delay(1200);
  if(providerMode==='permanent'){res.writeHead(400);res.end('{}');return;}
  if(providerMode==='retryable') {
    res.writeHead(503,{'Content-Type':'application/json','Retry-After':'3'});
    res.end(JSON.stringify({error:{message:'Temporary provider outage: test-secret-only sk-private-test Bearer private-header\nRetry later.'}}));return;
  }
  res.setHeader('Content-Type','application/json');
  if(payload.search_domain_filter) {
    res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({status:'ok',markdown:'# Retrieved product\nBrand: TestBrand'})}}],citations:providerMode==='no-citations'?[]:payload.search_domain_filter}));return;
  }
  const webUsed=payload.messages.some((message:any)=>message.content.includes('Retrieved product'));
  res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({qa_status:'pass',confidence:'high',summary:'Matches source',issue_count:0,issues:[],source_notes:{sap_used:true,url_used:webUsed,source_conflicts:[]}})}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));
});
const listen=(s:ReturnType<typeof createServer>)=>new Promise<void>(resolve=>s.listen(0,'127.0.0.1',resolve));
try {
  await initializeDatabase(pool);
  await initializeQaConfiguration(drizzle(pool,{schema}));
  await initializeAuth(pool); await initializeProvider(pool); await initializeJobRuns(pool); await verifySchema(pool);
  // Also exercise idempotent startup migrations.
  await initializeDatabase(pool);
  await listen(provider);
  const providerAddress=provider.address() as any;
  process.env.LLM_BASE_URL=`http://127.0.0.1:${providerAddress.port}/v1`;process.env.LLM_API_KEY='test-secret-only';
  process.env.NODE_ENV='test';
  const app=express();app.use(express.json());
  server.on('request',app);await listen(server);
  const origin=`http://127.0.0.1:${(server.address() as any).port}`;process.env.APP_ORIGIN=origin;
  registerAuth(app,pool);registerCatalogRoutes(app,pool);registerProviderRoutes(app,pool,scrape);registerJobRunRoutes(app,pool);registerQaConfigurationRoutes(app,drizzle(pool,{schema}));
  app.use((err:any,_req:any,res:any,_next:any)=>res.status(err instanceof ApiError||err instanceof ProviderError?err.status:err.code==='23505'?409:503).json({error:err.message}));
  const password='test-only-strong-password';
  const hash=await hashPassword(password);
  await pool.query("INSERT INTO users(id,username,password,role) VALUES ('admin','Administrator',$1,'admin'),('user','Operator',$1,'user'),('other','Other',$1,'user')",[hash]);
  const request=async(path:string,method='GET',body?:unknown,cookie='',requestOrigin=origin)=>{
    const response=await fetch(origin+path,{method,headers:{Origin:requestOrigin,'Content-Type':'application/json',Cookie:cookie},...(body===undefined?{}:{body:JSON.stringify(body)})});
    return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')};
  };
  assert.equal((await request('/api/catalog')).status,401);
  assert.equal((await request('/api/catalog','GET',undefined,'paxth_qa_user_session={"role":"admin"}')).status,401);
  assert.equal((await request('/api/auth/login','POST',{username:'Administrator',password},'','https://evil.example')).status,403);
  const adminLogin=await request('/api/auth/login','POST',{username:'administrator',password});assert.equal(adminLogin.status,200);
  assert.match(adminLogin.cookie!,/HttpOnly/);assert.match(adminLogin.cookie!,/SameSite=Strict/);assert.doesNotMatch(JSON.stringify(adminLogin.body),/password|scrypt/);
  const admin=adminLogin.cookie!.split(';')[0];
  assert.equal((await request('/api/users','POST',{username:'Temporary',password,role:'user'},admin)).status,201);
  assert.equal((await request('/api/users','POST',{username:' temporary ',password,role:'user'},admin)).status,409);
  const user=(await request('/api/auth/login','POST',{username:'Operator',password})).cookie!.split(';')[0];
  const other=(await request('/api/auth/login','POST',{username:'Other',password})).cookie!.split(';')[0];
  const personal={...DEFAULT_SCRAPE_SETTINGS,mode:'js',wait:2500,scrolls:5};
  assert.equal((await request('/api/scraper-settings')).status,401);
  assert.deepEqual((await request('/api/scraper-settings','GET',undefined,user)).body,{...DEFAULT_SCRAPE_SETTINGS,configured:false});
  assert.equal((await request('/api/scraper-settings/test','POST',{},user)).body.code,'API_KEY_REQUIRED');
  assert.equal((await request('/api/scrape','POST',{url:'https://8.8.8.8/product'},user)).body.code,'API_KEY_REQUIRED');
  for(const invalid of [{userId:'other'},{wait:-1},{wait:30001},{scrolls:1.5},{stealth:'true'},{apiKey:'bad\nkey'}]) {
    assert.equal((await request('/api/scraper-settings','PUT',{...personal,...invalid},user)).status,400);
  }
  assert.equal((await request('/api/scraper-settings','PUT',{...personal,apiKey:'sgai-user-secret'},user,'https://evil.example')).status,403);
  const savedPersonal=await request('/api/scraper-settings','PUT',{...personal,apiKey:' sgai-user-secret '},user);
  assert.deepEqual(savedPersonal.body,{...personal,configured:true});
  assert.doesNotMatch(JSON.stringify(savedPersonal.body),/apiKey|sgai-user-secret/);
  assert.equal((await request('/api/scraper-settings','PUT',{...DEFAULT_SCRAPE_SETTINGS,apiKey:'sgai-other-secret'},other)).status,200);
  assert.equal((await request('/api/scraper-settings','GET',undefined,other)).body.mode,'auto');
  assert.equal((await request('/api/scraper-settings','PUT',personal,user)).body.configured,true,'Omitting the key preserves it');
  assert.equal((await pool.query("SELECT scrapegraph_api_key FROM users WHERE id='user'")).rows[0].scrapegraph_api_key,'sgai-user-secret');
  const originalFetch=globalThis.fetch;
  const testedKeys:string[]=[];
  let creditsStatus=200;
  globalThis.fetch=async(target,init)=>{
    if(String(target)==='https://v2-api.scrapegraphai.com/api/credits') {
      testedKeys.push(new Headers(init?.headers).get('SGAI-APIKEY')!);
      return Response.json(creditsStatus===200?{remaining:50,used:5,plan:'Test'}:{error:{message:'sgai-user-secret'}},{status:creditsStatus});
    }
    return originalFetch(target,init);
  };
  try {
    assert.deepEqual((await request('/api/scraper-settings/test','POST',{},user)).body,{remaining:50,used:5,plan:'Test'});
    assert.equal((await request('/api/scraper-settings/test','POST',{apiKey:'sgai-draft-secret'},user)).status,200);
    assert.deepEqual(testedKeys,['sgai-user-secret','sgai-draft-secret']);
    assert.equal((await pool.query("SELECT scrapegraph_api_key FROM users WHERE id='user'")).rows[0].scrapegraph_api_key,'sgai-user-secret','Testing never persists a draft key');
    creditsStatus=401;
    const invalidKey=await request('/api/scraper-settings/test','POST',{},user);
    assert.equal(invalidKey.status,502);assert.doesNotMatch(JSON.stringify(invalidKey.body),/sgai-user-secret/);
    assert.equal((await request('/api/auth/me','GET',undefined,user)).status,200,'Upstream key failures preserve the session');
  } finally {globalThis.fetch=originalFetch;}
  assert.equal((await request('/api/scraper-settings','PUT',{...personal,apiKey:null},user)).body.configured,false);
  assert.equal((await request('/api/scraper-settings','GET',undefined,other)).body.configured,true,'Removing a key affects only its owner');
  assert.equal((await request('/api/scraper-settings','PUT',{...personal,apiKey:'sgai-user-secret'},user)).status,200);
  await initializeAuth(pool);
  assert.deepEqual((await request('/api/scraper-settings','GET',undefined,user)).body,{...personal,configured:true},'Repeat migrations preserve personal settings');
  assert.doesNotMatch(JSON.stringify((await request('/api/users','GET',undefined,admin)).body),/scrapegraph|sgai-user-secret|sgai-other-secret/);
  assert.equal((await request('/api/users','GET',undefined,user)).status,403);
  assert.equal((await request('/api/catalog','DELETE',{all:true},user)).status,403);
  assert.equal((await request('/api/provider-settings','PUT',{},user)).status,403);
  assert.equal((await request('/api/chat','POST',{},user)).status,403);
  await pool.query("INSERT INTO users(id,username,password,role) VALUES('legacy-admin','Legacy','unusable-plaintext','admin')");
  assert.equal((await request('/api/users/admin','DELETE',undefined,admin)).status,409);
  assert.equal((await request('/api/users/admin','PUT',{role:'user'},admin)).status,409);
  const settings=await request('/api/provider-settings','GET',undefined,user);
  assert.equal(settings.status,200);assert.doesNotMatch(JSON.stringify(settings.body),/test-secret-only|apiKey/);
  assert.equal(settings.body.scrapperModelName,'perplexity/sonar');
  assert.equal(settings.body.baseUrl,'','The gateway destination remains server-only');
  assert.equal(settings.body.modelName,'deepseek/deepseek-v4.1-flash');
  const configured={...editableSettings(DEFAULT_SETTINGS),modelName:'deepseek/deepseek-v4.1-flash',scrapperModelName:'test/sonar',maxTokens:10000};
  assert.equal((await request('/api/provider-settings','PUT',configured,admin)).status,200);
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.scrapperModelName,'test/sonar');
  assert.equal((await request('/api/chat','POST',{modelName:'unsaved/qa'},admin)).status,200);
  assert.equal(providerRequests.at(-1).model,'unsaved/qa');
  assert.equal(providerRequests.at(-1).messages.length,1);
  assert.equal((await request('/api/chat','POST',{purpose:'scrapper',modelName:'unsaved/sonar'},admin)).status,200);
  assert.equal(providerRequests.at(-1).model,'unsaved/sonar');
  assert.equal(providerRequests.at(-1).messages.length,1);
  assert.equal(providerRequests.at(-1).search_domain_filter,undefined,'Both API tests send only connectivity prompts');
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.scrapperModelName,'test/sonar','Tests never save draft models');
  providerMode='no-citations';
  assert.equal((await request('/api/chat','POST',{purpose:'scrapper'},admin)).status,200,'Connectivity tests do not require retrieval citations');
  assert.equal((await request('/api/chat','POST',{purpose:'qa'},admin)).status,200,'QA connectivity remains independent of retrieval failures');
  providerMode='success';calls=0;
  assert.equal((await request('/api/scrape','POST',{url:'https://8.8.8.8/product?variant=42',modelName:'injected'},user)).status,400);
  assert.equal((await request('/api/scrape','POST',{url:'http://127.0.0.1/page'},user)).status,400);
  const retrieved=await request('/api/scrape','POST',{url:'https://8.8.8.8/product?variant=42'},user);
  assert.equal(retrieved.status,200);assert.deepEqual(Object.keys(retrieved.body),['markdown']);
  assert.deepEqual(scrapeConfigurations.at(-1),{...personal,apiKey:'sgai-user-secret'});
  assert.match(retrieved.body.markdown,/variant=42/);assert.equal(calls,0,'Scraping makes no provider calls');
  assert.doesNotMatch(JSON.stringify(providerRequests),/test-secret-only/);
  scrapeBlocked=true;
  assert.equal((await request('/api/scrape','POST',{url:'https://8.8.8.8/product'},user)).status,502);
  scrapeBlocked=false;providerMode='success';calls=0;
  assert.equal((await request('/api/chat','POST',{baseUrl:'http://evil',apiKey:'x'},admin)).status,400);
  const mappingRules='Brand must match SAP. Review every uploaded bullet point and preserve optional blank fields.';
  const testSet=(await request('/api/qa-configuration','GET',undefined,user)).body.attributeSets.find((set:any)=>set.name==='TestSet');
  assert.equal((await request(`/api/attribute-sets/${testSet.id}`,'PUT',{name:'TestSet',rulesMarkdown:mappingRules},admin)).status,200);
  const sku=(id:string)=>({sku:id,source:{sap:'Brand: TestBrand'},raw_row:{sku:id,attributes__brand:'TestBrand',attributes__bullet_point_7:'Extra supplied bullet',custom_optional:'',source__sap:'private template source'},upload_attributes:{brand:'TestBrand'},attribute_set:'TestSet',status:'ready'});
  assert.equal((await request('/api/catalog','POST',[sku('a'),{sku:'invalid'}],user)).status,400);
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.length,0);
  await pool.query("CREATE FUNCTION fail_import() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.sku='rollback' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_import BEFORE INSERT ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_import()");
  assert.equal((await request('/api/catalog','POST',[sku('a'),sku('rollback')],user)).status,503);
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.length,0);
  await pool.query('DROP TRIGGER fail_import ON sku_data');
  const inserted=await request('/api/catalog','POST',[sku('a'),sku('b')],user);assert.equal(inserted.body.inserted.length,2);
  const duplicate=await request('/api/catalog','POST',[{...sku('a'),source:{sap:'Overwrite?'}}],user);assert.deepEqual(duplicate.body.skipped,['a']);
  assert.equal((await request('/api/catalog/nope','PUT',{source:{sap:'x'}},user)).status,404);
  assert.equal((await request('/api/jobs','POST',{id:'bad',name:'Bad',skus:{a:true}},user)).status,400);
  const job=await request('/api/jobs','POST',{id:'job',name:'Job',skus:['a','b'],attribute_set:'TestSet'},user);assert.equal(job.status,201);
  const credentials={baseUrl:process.env.LLM_BASE_URL,key:process.env.LLM_API_KEY,legacyKey:process.env.AICREDITS_API_KEY};
  delete process.env.LLM_BASE_URL;delete process.env.LLM_API_KEY;delete process.env.AICREDITS_API_KEY;
  assert.equal((await request('/api/scrape','POST',{url:'https://8.8.8.8/product'},user)).status,200,'ScrapeGraph retrieval uses its own key, independently of LLM credentials');
  const missingProvider=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(missingProvider.status,503);
  assert.match(missingProvider.body.error,/LLM_BASE_URL.*LLM_API_KEY/,'Missing credentials return actionable configuration errors');
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM job_runs')).rows[0].count,0,'A failed preflight saves no run');
  process.env.LLM_API_KEY=credentials.key;
  const partialProvider=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(partialProvider.status,503);
  assert.match(partialProvider.body.error,/LLM_BASE_URL.*LLM_API_KEY/);
  process.env.LLM_BASE_URL=credentials.baseUrl;process.env.LLM_API_KEY=credentials.key;
  if(credentials.legacyKey===undefined)delete process.env.AICREDITS_API_KEY;else process.env.AICREDITS_API_KEY=credentials.legacyKey;
  // Start and cancel must read their committed result without checking out a second connection.
  assert.equal((await request('/api/jobs','POST',{id:'pool-check',name:'Pool check',skus:['a']},user)).status,201);
  const singlePool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${namespace}`,max:1,connectionTimeoutMillis:1000,query_timeout:1000});
  const singleApp=express();singleApp.use(express.json());
  singleApp.use((_req,res,next)=>{res.locals.user={id:'user',username:'Operator',role:'user'};next();});
  registerJobRunRoutes(singleApp,singlePool);
  const singleServer=createServer(singleApp);await listen(singleServer);
  try {
    const singleOrigin=`http://127.0.0.1:${(singleServer.address() as any).port}`;
    const accepted=await fetch(singleOrigin+'/api/jobs/pool-check/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:randomUUID(),mode:'all'})});
    assert.equal(accepted.status,202,'Starting a run works with a one-connection pool');
    const acceptedRun=await accepted.json() as any;
    const cancelled=await fetch(singleOrigin+`/api/job-runs/${acceptedRun.id}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
    assert.equal(cancelled.status,200,'Cancellation reads its committed result using the same connection');
    assert.equal((await cancelled.json() as any).status,'cancelling');
  } finally {
    await new Promise<void>(resolve=>singleServer.close(()=>resolve()));
    await singlePool.end();
    await pool.query("DELETE FROM jobs WHERE id='pool-check'");
  }
  const runBody={requestId:randomUUID(),mode:'all'};
  const [first,repeated]=await Promise.all([request('/api/jobs/job/runs','POST',runBody,user),request('/api/jobs/job/runs','POST',runBody,user)]);
  assert.equal(first.status,202);assert.equal(repeated.status,202);
  assert.equal(first.body.id,repeated.body.id,'Concurrent identical starts return the same accepted run');
  const run=first;
  assert.equal((await request('/api/jobs/job/runs','POST',runBody,user)).body.id,run.body.id);
  assert.equal((await request('/api/jobs/job/runs','POST',{...runBody,requestId:randomUUID()},user)).status,409);
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,409);
  assert.equal((await request(`/api/job-runs/${run.body.id}/cancel`,'POST',{},other)).status,403);
  const waitFor=async(check:()=>Promise<boolean>,label:string)=>{
    for(let i=0;i<160;i++){if(await check())return;await delay(100);}throw new Error(`Timed out: ${label}`);
  };
  providerMode='wait';stopWorker=startJobWorker(pool,scrape);stopSecond=startJobWorker(pool,scrape);
  await waitFor(async()=>calls>=1,'first provider call');
  await request('/api/catalog/a','PUT',{source:{sap:'New evidence'}},user);
  await waitFor(async()=>(await request(`/api/job-runs/${run.body.id}`,'GET',undefined,user)).body.status==='completed','run completion');
  assert.equal(calls,2,'Two workers must not duplicate calls');
  const history=(await request(`/api/job-runs/${run.body.id}`,'GET',undefined,user)).body;
  assert.equal(history.items[0].snapshot.source.sap,'Brand: TestBrand');assert.ok(history.items[0].result.qa_result);
  const current=(await request('/api/catalog','GET',undefined,user)).body;
  assert.equal(current.find((row:any)=>row.sku==='a').source.sap,'New evidence');assert.ok(!current.find((row:any)=>row.sku==='a').qa_result,'New evidence must not acquire stale result');
  await stopWorker();stopWorker=undefined;await stopSecond();stopSecond=undefined;
  // Simulate an interrupted run with one saved item and a consumed attempt on the other.
  const restarts=await Promise.all([request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user),request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user)]);
  assert.deepEqual(restarts.map(response=>response.status).sort(),[202,409],'Concurrent distinct starts accept one run and report an active-run conflict');
  const restart=restarts.find(response=>response.status===202)!;
  await pool.query("UPDATE job_runs SET status='running',owner_token='old-owner',started_at=now() WHERE id=$1",[restart.body.id]);
  await pool.query("UPDATE job_run_items SET status='completed',result=$2 WHERE run_id=$1 AND sku='b'",[restart.body.id,JSON.stringify(history.items[1].result)]);
  await pool.query("UPDATE job_run_items SET status='running',attempts=1,started_at=now(),error='QA attempt 1: The model request timed out.' WHERE run_id=$1 AND sku='a'",[restart.body.id]);
  providerMode='success';const before=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${restart.body.id}`,'GET',undefined,user)).body.status==='completed','restart recovery');
  assert.equal(calls,before+1);
  const recoveredItem=(await pool.query("SELECT attempts,error,result FROM job_run_items WHERE run_id=$1 AND sku='a'",[restart.body.id])).rows[0];
  assert.equal(recoveredItem.attempts,2);assert.equal(recoveredItem.error,null);assert.equal(recoveredItem.result.error,null,'Successful recovery clears the previous transient failure');
  // Saving a paid result retries only the DB commit.
  await pool.query("CREATE SEQUENCE fail_save_seq; CREATE FUNCTION fail_save() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.result IS NOT NULL AND nextval('fail_save_seq')=1 THEN RAISE EXCEPTION 'injected save failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_save BEFORE UPDATE ON job_run_items FOR EACH ROW EXECUTE FUNCTION fail_save()");
  const beforeSave=calls;const saveRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await waitFor(async()=>(await request(`/api/job-runs/${saveRun.body.id}`,'GET',undefined,user)).body.status==='completed','save retry');
  assert.equal(calls,beforeSave+1,'DB retry must not make a second provider request');
  await pool.query('DROP TRIGGER fail_save ON job_run_items');
  providerMode='permanent';const beforeError=calls;
  const failed=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await waitFor(async()=>(await request(`/api/job-runs/${failed.body.id}`,'GET',undefined,user)).body.status==='failed','permanent provider error');
  assert.equal(calls,beforeError+1);
  // The retry cause is committed before backoff and survives worker interruption.
  providerMode='retryable';const beforeInterruption=calls;
  const interrupted=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  let recordedFailure='';
  await waitFor(async()=>{
    const item=(await pool.query("SELECT attempts,error FROM job_run_items WHERE run_id=$1 AND sku='a'",[interrupted.body.id])).rows[0];
    if(item.attempts===1&&item.error?.includes('HTTP 503')){recordedFailure=item.error;return true;}return false;
  },'durable transient provider failure');
  await stopWorker();stopWorker=undefined;
  assert.equal(calls,beforeInterruption+1,'Stopping during retry backoff prevents another dispatch');
  assert.match(recordedFailure,/QA attempt 1:.*HTTP 503.*Temporary provider outage/);
  assert.match(recordedFailure,/\[redacted\]/);assert.doesNotMatch(recordedFailure,/test-secret-only|sk-private-test|private-header|\n/);
  const interruptedHistory=(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body;
  assert.equal(interruptedHistory.items[0].error,recordedFailure);
  await pool.query("UPDATE job_run_items SET attempts=3 WHERE run_id=$1 AND sku='a'",[interrupted.body.id]);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body.status==='failed','exhausted recovery retains the provider failure');
  assert.equal(calls,beforeInterruption+1,'An exhausted resumed item never dispatches another paid request');
  const retainedFailure=(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body.items[0].error;
  assert.ok(retainedFailure.includes(recordedFailure));assert.match(retainedFailure,/fresh run/i);
  assert.doesNotMatch(retainedFailure,/test-secret-only|sk-private-test|private-header/);
  providerMode='wait';const beforeCancel=calls;
  const cancelled=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  await waitFor(async()=>calls>beforeCancel,'inflight cancel');
  assert.equal((await request(`/api/job-runs/${cancelled.body.id}/cancel`,'POST',{},user)).status,200);
  await waitFor(async()=>(await request(`/api/job-runs/${cancelled.body.id}`,'GET',undefined,user)).body.status==='cancelled','cancelled');
  assert.equal(calls,beforeCancel+1,'Cancel prevents dispatching the next SKU');
  await stopWorker();stopWorker=undefined;
  // Neither a restart nor a future retry may reset a consumed budget or deadline.
  const exhausted=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await pool.query("UPDATE job_run_items SET attempts=3 WHERE run_id=$1 AND sku='a'",[exhausted.body.id]);
  const beforeExhaustion=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${exhausted.body.id}`,'GET',undefined,user)).body.status==='failed','exhausted attempts');
  assert.equal(calls,beforeExhaustion);
  const exhaustionError=(await request(`/api/job-runs/${exhausted.body.id}`,'GET',undefined,user)).body.items[0].error;
  assert.match(exhaustionError,/interrupted.*fresh run/i,'Without a saved cause, exhausted recovery explains interruption and a fresh rerun');
  await stopWorker();stopWorker=undefined;
  const expired=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await pool.query("UPDATE job_run_items SET started_at=now()-interval '6 minutes' WHERE run_id=$1 AND sku='a'",[expired.body.id]);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${expired.body.id}`,'GET',undefined,user)).body.status==='failed','expired item deadline');
  assert.equal(calls,beforeExhaustion);
  await stopWorker();stopWorker=undefined;
  // Browser retrieval is independent of legacy model settings; QA retains its run snapshot.
  const productUrl='https://8.8.8.8/product?variant=42';
  assert.equal((await request('/api/catalog/b','PUT',{source:{sap:'Brand: TestBrand',url:productUrl},scraped_markdown:''},user)).status,200);
  const webRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  await request('/api/scraper-settings','PUT',{...personal,apiKey:'sgai-rotated-secret'},user);
  const snapshotConfig=(await pool.query('SELECT configuration FROM job_runs WHERE id=$1',[webRun.body.id])).rows[0].configuration;
  assert.equal(snapshotConfig.settings.scrapperModelName,'test/sonar');assert.ok(!('selectors' in snapshotConfig));
  assert.doesNotMatch(JSON.stringify(snapshotConfig),/test-secret-only|apiKey|sgai-.*-secret/);
  await request('/api/provider-settings','PUT',{...configured,modelName:'next/qa',scrapperModelName:'next/sonar'},admin);
  providerMode='success';let offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${webRun.body.id}`,'GET',undefined,user)).body.status==='completed','snapshotted retrieval');
  await stopWorker();stopWorker=undefined;
  assert.deepEqual(providerRequests.slice(offset).map(payload=>payload.model),['deepseek/deepseek-v4.1-flash']);
  assert.equal(scrapeRequests.at(-1),productUrl);
  assert.equal(scrapeConfigurations.at(-1)?.apiKey,'sgai-rotated-secret','Queued jobs load the actor\'s latest key instead of another user\'s key or a snapshot');
  assert.equal(scrapeConfigurations.at(-1)?.mode,'js');
  const qaRequest=providerRequests[offset];
  assert.equal(qaRequest.reasoning_effort,'low');assert.equal(qaRequest.max_tokens,10000);
  assert.deepEqual(qaRequest.response_format,{type:'json_object'});assert.ok(qaRequest.messages[0].content.includes(mappingRules));
  assert.match(qaRequest.messages[0].content,/SAP takes precedence/);
  const qaData=JSON.parse(qaRequest.messages[1].content);
  assert.equal(qaData.attribute_set,'TestSet');assert.equal(qaData.source_sap,'Brand: TestBrand');assert.equal(qaData.source_url,productUrl);
  assert.match(qaData.scraped_markdown,/Retrieved product/);
  assert.deepEqual(qaData.uploaded_template,{sku:'b',attributes__brand:'TestBrand',attributes__bullet_point_7:'Extra supplied bullet',custom_optional:''},'QA receives every original upload field without source-only columns');
  const webHistory=(await request(`/api/job-runs/${webRun.body.id}`,'GET',undefined,user)).body;
  assert.match(webHistory.items[1].result.scraped_markdown,/Retrieved product/);
  assert.doesNotMatch(JSON.stringify(webHistory),/sgai-.*-secret|apiKey/);
  assert.equal(webHistory.items[1].error,null);assert.equal(webHistory.items[1].result.qa_result.qa_status,'pass');
  assert.deepEqual(webHistory.items[1].result.qa_result.source_notes,{sap_used:true,url_used:true,source_conflicts:[]});
  assert.match((await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='b').scraped_markdown,/variant=42/);
  // Old job snapshots still retrieve with the browser without rewriting stored configuration.
  await pool.query("UPDATE sku_data SET scraped_markdown=NULL,scrape_status=NULL WHERE sku='b'");
  const legacyRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  await pool.query("UPDATE job_runs SET configuration=jsonb_set(configuration,'{settings}',(configuration->'settings')-'scrapperModelName') WHERE id=$1",[legacyRun.body.id]);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${legacyRun.body.id}`,'GET',undefined,user)).body.status==='completed','legacy retrieval defaults');
  await stopWorker();stopWorker=undefined;
  assert.equal(providerRequests[offset].model,'next/qa');
  assert.equal(providerRequests.length-offset,1);
  assert.equal(scrapeRequests.at(-1),productUrl);
  // Keep the actual browser failure when no other evidence exists; never spend QA tokens on it.
  await pool.query("UPDATE sku_data SET source=$1,scraped_markdown=NULL,scrape_status=NULL WHERE sku='b'",[JSON.stringify({url:productUrl})]);
  scrapeBlocked=true;
  const blockedRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${blockedRun.body.id}`,'GET',undefined,user)).body.status==='failed','blocked page retains its browser error');
  await stopWorker();stopWorker=undefined;scrapeBlocked=false;
  const blockedItem=(await request(`/api/job-runs/${blockedRun.body.id}`,'GET',undefined,user)).body.items.find((item:any)=>item.sku==='b');
  assert.match(blockedItem.error,/website blocked browser access/);
  assert.equal(blockedItem.result.scrape_status,'failed');
  assert.equal(providerRequests.length,offset,'No QA request without usable source evidence');
  await initializeDatabase(pool); // Existing populated records remain readable after restart migrations.
  // Clear remains all-or-nothing even if catalog deletion fails after deleting jobs.
  await pool.query("CREATE FUNCTION fail_clear() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected clear failure'; END $$; CREATE TRIGGER fail_clear BEFORE DELETE ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_clear()");
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,503);
  assert.equal((await request('/api/jobs','GET',undefined,user)).body.length,1);
  await pool.query('DROP TRIGGER fail_clear ON sku_data');
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,200);
  assert.equal((await request('/api/jobs','GET',undefined,user)).body.length,0);
  await request('/api/users/user','PUT',{password:'replacement-test-password'},admin);
  assert.equal((await request('/api/catalog','GET',undefined,user)).status,401);
  await pool.query('UPDATE sessions SET expires_at=now()-interval \'1 second\' WHERE token_hash=$1',[hashSessionToken(other.split('=')[1])]);
  assert.equal((await request('/api/catalog','GET',undefined,other)).status,401);
  await request('/api/auth/logout','POST',undefined,admin);
  assert.equal((await request('/api/catalog','GET',undefined,admin)).status,401);
  // Retired selector data never blocks startup and is left untouched.
  await pool.query("CREATE TABLE site_selectors(id text PRIMARY KEY,website text,selectors text); INSERT INTO site_selectors VALUES('one','Example.com','main'),('two','www.example.com','article')");
  await initializeDatabase(pool);await verifySchema(pool);
  assert.equal((await pool.query('SELECT * FROM site_selectors')).rowCount,2);
  assert.equal((await pool.query("SELECT website FROM site_selectors WHERE id='one'")).rows[0].website,'Example.com');
  console.log('Security/database checks passed: sessions, roles, atomic saves, recovery, ownership, cancellation, budgets, model snapshots, retrieval, and preserved legacy data.');
} finally {
  await stopWorker?.();await stopSecond?.();server.closeAllConnections();provider.closeAllConnections();
  await Promise.all([new Promise<void>(resolve=>server.close(()=>resolve())),new Promise<void>(resolve=>provider.close(()=>resolve()))]);
  await pool.end();await root.query(`DROP SCHEMA ${namespace} CASCADE`);await root.end();
}
