import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import express from 'express';
import {Pool} from 'pg';
import {drizzle} from 'drizzle-orm/node-postgres';
import * as schema from '../db/schema';
import {initializeQaConfiguration,registerQaConfigurationRoutes} from '../db/qaConfiguration';
import {initializeDatabase,verifySchema} from './database';
import {initializeAuth,registerAuth,hashPassword,hashSessionToken} from './auth';
import {initializeProvider,registerProviderRoutes} from './provider';
import {initializeJobRuns,registerJobRunRoutes,startJobWorker} from './jobRunner';
import {ApiError,registerCatalogRoutes} from './catalog';
import {ProviderError} from '../lib/chatCompletion';
import {validateScrapeInput, ScrapeError} from '../lib/browserScrape';
import {DEFAULT_SETTINGS,editableSettings} from '../lib/providerSettings';

assert.ok(process.env.TEST_DATABASE_URL,'Set TEST_DATABASE_URL to a disposable PostgreSQL instance. Production DATABASE_URL is never used.');
const namespace=`security_${randomUUID().replaceAll('-','')}`;
const root=new Pool({connectionString:process.env.TEST_DATABASE_URL});
await root.query(`CREATE SCHEMA ${namespace}`);
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${namespace}`,max:10,query_timeout:5000});
const server=createServer();
let stopWorker:(()=>Promise<void>)|undefined;
let stopSecond:(()=>Promise<void>)|undefined;
let calls=0, providerMode='success';
const providerRequests:any[]=[];
const scrapeRequests:string[]=[];
let scrapeBlocked=false;
let duringScrape: (()=>Promise<void>) | undefined;
const scrape=async(rawUrl:string, signal:AbortSignal)=>{
  const {url}=validateScrapeInput({url:rawUrl});signal.throwIfAborted();scrapeRequests.push(url);
  await duringScrape?.();signal.throwIfAborted();
  if(scrapeBlocked)throw new ScrapeError('The website blocked browser access.',502,'PAGE_BLOCKED');
  return {markdown:'# Retrieved product\nBrand: TestBrand\n\nSource: <'+url+'>',requestedUrl:url,finalUrl:url};
};
const provider=createServer(async(req,res)=>{
  let raw='';for await(const chunk of req) raw+=chunk;
  const payload=JSON.parse(raw);providerRequests.push(payload);
  calls++;
  if(providerMode==='wait') await delay(1200);
  if(providerMode==='permanent'){res.writeHead(400);res.end('{}');return;}
  if(providerMode==='retryable') {
    res.writeHead(503,{'Content-Type':'application/json','Retry-After':'3'});
    res.end(JSON.stringify({error:{message:'Temporary provider outage: test-secret-only sk-private-test Bearer private-header\nRetry later.'}}));return;
  }
  res.setHeader('Content-Type','application/json');
  if(payload.search_domain_filter) {
    res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({status:'ok',markdown:'# Retrieved product\nBrand: TestBrand'})}}],citations:providerMode==='no-citations'?[]:payload.search_domain_filter}));return;
  }
  const webUsed=payload.messages.some((message:any)=>message.content.includes('Retrieved product'));
  let sapUsed=false;
  try { sapUsed=Boolean(JSON.parse(payload.messages.find((message:any)=>message.role==='user').content).source_sap); } catch { /* Connectivity tests have no source payload. */ }
  res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({qa_status:'pass',confidence:'high',summary:'Matches source',issue_count:0,issues:[],source_notes:{sap_used:sapUsed,url_used:webUsed,source_conflicts:[]}})}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));
});
const listen=(s:ReturnType<typeof createServer>)=>new Promise<void>(resolve=>s.listen(0,'127.0.0.1',resolve));
try {
  await initializeDatabase(pool);
  await initializeQaConfiguration(drizzle(pool,{schema}));
  await initializeAuth(pool); await initializeProvider(pool); await initializeJobRuns(pool); await verifySchema(pool);
  // Also exercise idempotent startup migrations.
  await initializeDatabase(pool);
  await listen(provider);
  const providerAddress=provider.address() as any;
  process.env.LLM_BASE_URL=`http://127.0.0.1:${providerAddress.port}/v1`;process.env.LLM_API_KEY='test-secret-only';
  process.env.NODE_ENV='test';
  const app=express();app.use(express.json());
  server.on('request',app);await listen(server);
  const origin=`http://127.0.0.1:${(server.address() as any).port}`;process.env.APP_ORIGIN=origin;
  registerAuth(app,pool);registerCatalogRoutes(app,pool,scrape);registerProviderRoutes(app,pool);
  registerJobRunRoutes(app,pool);registerQaConfigurationRoutes(app,drizzle(pool,{schema}));
  app.use('/api', (_req,res)=>res.status(404).json({error:'Not found'}));
  app.use((err:any,_req:any,res:any,_next:any)=>res.status(err instanceof ApiError||err instanceof ProviderError?err.status:err.code==='23505'?409:503).json({error:err.message}));
  const password='test-only-strong-password';
  const hash=await hashPassword(password);
  await pool.query("INSERT INTO users(id,username,password,role) VALUES ('admin','Administrator',$1,'admin'),('user','Operator',$1,'user'),('other','Other',$1,'user')",[hash]);
  const request=async(path:string,method='GET',body?:unknown,cookie='',requestOrigin=origin)=>{
    const response=await fetch(origin+path,{method,headers:{Origin:requestOrigin,'Content-Type':'application/json',Cookie:cookie},...(body===undefined?{}:{body:JSON.stringify(body)})});
    return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')};
  };
  assert.equal((await request('/api/catalog')).status,401);
  assert.equal((await request('/api/catalog','GET',undefined,'paxth_qa_user_session={"role":"admin"}')).status,401);
  assert.equal((await request('/api/auth/login','POST',{username:'Administrator',password},'','https://evil.example')).status,403);
  const adminLogin=await request('/api/auth/login','POST',{username:'administrator',password});assert.equal(adminLogin.status,200);
  assert.match(adminLogin.cookie!,/HttpOnly/);assert.match(adminLogin.cookie!,/SameSite=Strict/);assert.doesNotMatch(JSON.stringify(adminLogin.body),/password|scrypt/);
  const admin=adminLogin.cookie!.split(';')[0];
  assert.equal((await request('/api/users','POST',{username:'Temporary',password,role:'user'},admin)).status,201);
  assert.equal((await request('/api/users','POST',{username:' temporary ',password,role:'user'},admin)).status,409);
  const user=(await request('/api/auth/login','POST',{username:'Operator',password})).cookie!.split(';')[0];
  const other=(await request('/api/auth/login','POST',{username:'Other',password})).cookie!.split(';')[0];
  const edit=async(id:string,updates:Record<string,unknown>)=>request(`/api/catalog/${id}`,'PUT',{
    ...updates,expectedRevision:(await pool.query('SELECT revision FROM sku_data WHERE sku=$1',[id])).rows[0]?.revision ?? 0,
  },user);
  for(const [path,method] of [['/api/scraper-settings','GET'],['/api/scraper-settings','PUT'],['/api/scraper-settings/test','POST']]) {
    assert.equal((await request(path,method,method==='GET'?undefined:{},user)).status,404,'Retired personal settings are inaccessible');
  }
  await pool.query("ALTER TABLE users ADD COLUMN scrapegraph_api_key text; ALTER TABLE users ADD COLUMN scrapegraph_settings jsonb; UPDATE users SET scrapegraph_api_key='sgai-retired-secret',scrapegraph_settings='{\"mode\":\"js\"}' WHERE id='user'");
  await initializeAuth(pool);
  assert.equal((await pool.query("SELECT scrapegraph_api_key FROM users WHERE id='user'")).rows[0].scrapegraph_api_key,'sgai-retired-secret','Retired columns survive migrations');
  assert.doesNotMatch(JSON.stringify((await request('/api/users','GET',undefined,admin)).body),/scrapegraph|sgai-retired-secret/);
  assert.equal((await request('/api/users','GET',undefined,user)).status,403);
  assert.equal((await request('/api/catalog','DELETE',{all:true},user)).status,403);
  assert.equal((await request('/api/provider-settings','PUT',{},user)).status,403);
  assert.equal((await request('/api/chat','POST',{},user)).status,403);
  await pool.query("INSERT INTO users(id,username,password,role) VALUES('legacy-admin','Legacy','unusable-plaintext','admin')");
  assert.equal((await request('/api/users/admin','DELETE',undefined,admin)).status,409);
  assert.equal((await request('/api/users/admin','PUT',{role:'user'},admin)).status,409);
  const settings=await request('/api/provider-settings','GET',undefined,user);
  assert.equal(settings.status,200);assert.doesNotMatch(JSON.stringify(settings.body),/test-secret-only|apiKey/);
  assert.ok(!('scrapperModelName' in settings.body));
  assert.equal(settings.body.baseUrl,'','The gateway destination remains server-only');
  assert.equal(settings.body.modelName,'deepseek/deepseek-v4.1-flash');
  await pool.query("UPDATE provider_settings SET settings='{\"modelName\":\"legacy/qa\",\"scrapperModelName\":\"perplexity/sonar\"}' WHERE id='default'");
  await initializeProvider(pool);
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.modelName,'legacy/qa');
  assert.equal((await request('/api/provider-settings','PUT',{...editableSettings(DEFAULT_SETTINGS),scrapperModelName:'perplexity/sonar'},admin)).status,400);
  await initializeProvider(pool);
  assert.ok(!('scrapperModelName' in (await pool.query("SELECT settings FROM provider_settings WHERE id='default'")).rows[0].settings));
  const configured={...editableSettings(DEFAULT_SETTINGS),modelName:'deepseek/deepseek-v4.1-flash',maxTokens:10000};
  assert.equal((await request('/api/provider-settings','PUT',configured,admin)).status,200);
  assert.ok(!('scrapperModelName' in (await request('/api/provider-settings','GET',undefined,user)).body));
  assert.equal((await request('/api/chat','POST',{modelName:'unsaved/qa'},admin)).status,200);
  assert.equal(providerRequests.at(-1).model,'unsaved/qa');
  assert.equal(providerRequests.at(-1).messages.length,1);
  assert.equal((await request('/api/chat','POST',{purpose:'scrapper',modelName:'unsaved/sonar'},admin)).status,400);
  assert.equal((await request('/api/provider-settings','GET',undefined,user)).body.modelName,configured.modelName,'Tests never save draft models');
  providerMode='no-citations';
  assert.equal((await request('/api/chat','POST',{purpose:'scrapper'},admin)).status,400);
  assert.equal((await request('/api/chat','POST',{purpose:'qa'},admin)).status,200,'QA connectivity remains independent of retrieval failures');
  providerMode='success';calls=0;
  assert.equal((await request('/api/scrape','POST',{url:'https://8.8.8.8/product'},user)).status,404);
  assert.equal((await request('/api/catalog/nope/scrape','POST',{expectedRevision:0,url:'https://8.8.8.8/product'},user)).status,400);
  assert.equal((await request('/api/catalog/nope/scrape','POST',{expectedRevision:0},user)).status,404);
  assert.equal(calls,0,'Scraping makes no provider calls');
  assert.doesNotMatch(JSON.stringify(providerRequests),/test-secret-only/);
  providerMode='success';calls=0;
  assert.equal((await request('/api/chat','POST',{baseUrl:'http://evil',apiKey:'x'},admin)).status,400);
  const mappingRules='Brand must match SAP. Review every uploaded bullet point and preserve optional blank fields.';
  const testSet=(await request('/api/qa-configuration','GET',undefined,user)).body.attributeSets.find((set:any)=>set.name==='TestSet');
  assert.equal((await request(`/api/attribute-sets/${testSet.id}`,'PUT',{name:'TestSet',rulesMarkdown:mappingRules},admin)).status,200);
  const sku=(id:string)=>({sku:id,source:{sap:'Brand: TestBrand'},raw_row:{sku:id,attributes__brand:'TestBrand',attributes__bullet_point_7:'Extra supplied bullet',custom_optional:'',source__sap:'private template source'},upload_attributes:{brand:'TestBrand'},attribute_set:'TestSet',status:'ready'});
  assert.equal((await request('/api/catalog','POST',[sku('a'),{sku:'invalid'}],user)).status,400);
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.length,0);
  for(const qa_result of [null,'forged',{qa_status:'pass',issues:[]}]) {
    const rejected=await request('/api/catalog','POST',[sku('valid-before-forged'),{...sku('forged'),raw_row:{sku:'forged',qa_result}}],user);
    assert.equal(rejected.status,400);
    assert.equal(rejected.body.error,'raw_row.qa_result is reserved for server-generated QA; remove it before importing.');
    assert.equal((await pool.query('SELECT count(*)::int AS count FROM sku_data')).rows[0].count,0);
  }
  assert.equal((await request('/api/catalog','POST',[{...sku('forged'),qa_result:{qa_status:'pass'}}],user)).status,400);
  await pool.query("CREATE FUNCTION fail_import() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.sku='rollback' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_import BEFORE INSERT ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_import()");
  assert.equal((await request('/api/catalog','POST',[sku('a'),sku('rollback')],user)).status,503);
  assert.equal((await request('/api/catalog','GET',undefined,user)).body.length,0);
  await pool.query('DROP TRIGGER fail_import ON sku_data');
  const inserted=await request('/api/catalog','POST',[sku('a'),sku('b')],user);assert.equal(inserted.body.inserted.length,2);
  const duplicate=await request('/api/catalog','POST',[{...sku('a'),source:{sap:'Overwrite?'}}],user);assert.deepEqual(duplicate.body.skipped,['a']);
  assert.equal((await request('/api/catalog/nope','PUT',{source:{sap:'x'},expectedRevision:0},user)).status,404);
  assert.equal((await request('/api/jobs','POST',{id:'bad',name:'Bad',skus:{a:true}},user)).status,400);
  const job=await request('/api/jobs','POST',{id:'job',name:'Job',skus:['a','b'],attribute_set:'TestSet'},user);assert.equal(job.status,201);
  const credentials={baseUrl:process.env.LLM_BASE_URL,key:process.env.LLM_API_KEY,legacyKey:process.env.AICREDITS_API_KEY};
  delete process.env.LLM_BASE_URL;delete process.env.LLM_API_KEY;delete process.env.AICREDITS_API_KEY;
  await request('/api/catalog','POST',[{...sku('scrape-check'),source:{url:'https://8.8.8.8/product?variant=42'}}],user);
  const scraped=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user);
  assert.equal(scraped.status,200,'Scraping works without any LLM credentials');
  assert.equal(scraped.body.sku,'scrape-check');assert.equal(scraped.body.revision,1);
  assert.equal(scraped.body.scrape_metadata.method,'browser');assert.match(scraped.body.scraped_markdown,/variant=42/);
  assert.equal(calls,0);
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user)).status,409);
  assert.equal((await request('/api/catalog/scrape-check','PUT',{source:{sap:'missing revision'}},user)).status,400);
  assert.equal((await request('/api/catalog/scrape-check','PUT',{expectedRevision:0,source:{sap:'stale'}},user)).status,409);
  scrapeBlocked=true;
  const failure=await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user);
  assert.equal(failure.status,502);scrapeBlocked=false;
  const afterFailure=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='scrape-check');
  assert.equal(afterFailure.scraped_markdown,scraped.body.scraped_markdown);assert.equal(afterFailure.revision,1);
  assert.deepEqual(afterFailure.scrape_metadata,scraped.body.scrape_metadata);assert.match(afterFailure.scrape_error,/blocked/);
  await pool.query("CREATE FUNCTION fail_scrape_save() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.sku='scrape-check' AND NEW.scrape_status='success' THEN RAISE EXCEPTION 'injected scrape commit failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_scrape_save BEFORE UPDATE ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_scrape_save()");
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user)).status,503,'A failed evidence commit is never reported as saved');
  assert.equal((await pool.query("SELECT revision FROM sku_data WHERE sku='scrape-check'")).rows[0].revision,1);
  await pool.query('DROP TRIGGER fail_scrape_save ON sku_data');
  duringScrape=async()=>{assert.equal((await edit('scrape-check',{source:{url:'https://8.8.8.8/changed'}})).status,200);};
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:1},user)).status,409);
  duringScrape=undefined;
  const changed=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='scrape-check');
  assert.equal(changed.source.url,'https://8.8.8.8/changed');assert.equal(changed.scraped_markdown,scraped.body.scraped_markdown);
  duringScrape=async()=>{
    await pool.query("DELETE FROM sku_data WHERE sku='scrape-check'");
    await request('/api/catalog','POST',[{...sku('scrape-check'),source:{url:'https://8.8.8.8/reimported'}}],user);
  };
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:2},user)).status,409,'Deleted/reimported SKU cannot receive evidence from an old row');
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user)).status,409,'Row identity protects deletion/reimport even when both revisions are zero');
  duringScrape=async()=>{await pool.query("DELETE FROM sku_data WHERE sku='scrape-check'");};
  assert.equal((await request('/api/catalog/scrape-check/scrape','POST',{expectedRevision:0},user)).status,404);
  duringScrape=undefined;
  await request('/api/catalog','DELETE',{skus:['scrape-check']},admin);
  const missingProvider=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(missingProvider.status,503);
  assert.match(missingProvider.body.error,/LLM_BASE_URL.*LLM_API_KEY/,'Missing credentials return actionable configuration errors');
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM job_runs')).rows[0].count,0,'A failed preflight saves no run');
  process.env.LLM_API_KEY=credentials.key;
  const partialProvider=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(partialProvider.status,503);
  assert.match(partialProvider.body.error,/LLM_BASE_URL.*LLM_API_KEY/);
  process.env.LLM_BASE_URL=credentials.baseUrl;process.env.LLM_API_KEY=credentials.key;
  if(credentials.legacyKey===undefined)delete process.env.AICREDITS_API_KEY;else process.env.AICREDITS_API_KEY=credentials.legacyKey;
  // Start and cancel must read their committed result without checking out a second connection.
  assert.equal((await request('/api/jobs','POST',{id:'pool-check',name:'Pool check',skus:['a']},user)).status,201);
  const singlePool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${namespace}`,max:1,connectionTimeoutMillis:1000,query_timeout:1000});
  const singleApp=express();singleApp.use(express.json());
  singleApp.use((_req,res,next)=>{res.locals.user={id:'user',username:'Operator',role:'user'};next();});
  registerJobRunRoutes(singleApp,singlePool);
  const singleServer=createServer(singleApp);await listen(singleServer);
  try {
    const singleOrigin=`http://127.0.0.1:${(singleServer.address() as any).port}`;
    const accepted=await fetch(singleOrigin+'/api/jobs/pool-check/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:randomUUID(),mode:'all'})});
    assert.equal(accepted.status,202,'Starting a run works with a one-connection pool');
    const acceptedRun=await accepted.json() as any;
    const cancelled=await fetch(singleOrigin+`/api/job-runs/${acceptedRun.id}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
    assert.equal(cancelled.status,200,'Cancellation reads its committed result using the same connection');
    assert.equal((await cancelled.json() as any).status,'cancelling');
  } finally {
    await new Promise<void>(resolve=>singleServer.close(()=>resolve()));
    await singlePool.end();
    await pool.query("DELETE FROM jobs WHERE id='pool-check'");
  }
  const runBody={requestId:randomUUID(),mode:'all'};
  const [first,repeated]=await Promise.all([request('/api/jobs/job/runs','POST',runBody,user),request('/api/jobs/job/runs','POST',runBody,user)]);
  assert.equal(first.status,202);assert.equal(repeated.status,202);
  assert.equal(first.body.id,repeated.body.id,'Concurrent identical starts return the same accepted run');
  const run=first;
  assert.equal((await request('/api/jobs/job/runs','POST',runBody,user)).body.id,run.body.id);
  assert.equal((await request('/api/jobs/job/runs','POST',{...runBody,requestId:randomUUID()},user)).status,409);
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,409);
  assert.equal((await request(`/api/job-runs/${run.body.id}/cancel`,'POST',{},other)).status,403);
  const waitFor=async(check:()=>Promise<boolean>,label:string)=>{
    for(let i=0;i<160;i++){if(await check())return;await delay(100);}throw new Error(`Timed out: ${label}`);
  };
  providerMode='wait';stopWorker=startJobWorker(pool,scrape);stopSecond=startJobWorker(pool,scrape);
  await waitFor(async()=>calls>=1,'first provider call');
  await edit('a',{source:{sap:'New evidence'}});
  await waitFor(async()=>(await request(`/api/job-runs/${run.body.id}`,'GET',undefined,user)).body.status==='completed','run completion');
  assert.equal(calls,2,'Two workers must not duplicate calls');
  const history=(await request(`/api/job-runs/${run.body.id}`,'GET',undefined,user)).body;
  assert.equal(history.items[0].snapshot.source.sap,'Brand: TestBrand');assert.ok(history.items[0].result.qa_result);
  const current=(await request('/api/catalog','GET',undefined,user)).body;
  assert.equal(current.find((row:any)=>row.sku==='a').source.sap,'New evidence');assert.ok(!current.find((row:any)=>row.sku==='a').qa_result,'New evidence must not acquire stale result');
  await stopWorker();stopWorker=undefined;await stopSecond();stopSecond=undefined;
  // Simulate an interrupted run with one saved item and a consumed attempt on the other.
  const restarts=await Promise.all([request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user),request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user)]);
  assert.deepEqual(restarts.map(response=>response.status).sort(),[202,409],'Concurrent distinct starts accept one run and report an active-run conflict');
  const restart=restarts.find(response=>response.status===202)!;
  await pool.query("UPDATE job_runs SET status='running',owner_token='old-owner',started_at=now() WHERE id=$1",[restart.body.id]);
  await pool.query("UPDATE job_run_items SET status='completed',result=$2 WHERE run_id=$1 AND sku='b'",[restart.body.id,JSON.stringify(history.items[1].result)]);
  await pool.query("UPDATE job_run_items SET status='running',attempts=1,started_at=now(),error='QA attempt 1: The model request timed out.' WHERE run_id=$1 AND sku='a'",[restart.body.id]);
  providerMode='success';const before=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${restart.body.id}`,'GET',undefined,user)).body.status==='completed','restart recovery');
  assert.equal(calls,before+1);
  const recoveredItem=(await pool.query("SELECT attempts,error,result FROM job_run_items WHERE run_id=$1 AND sku='a'",[restart.body.id])).rows[0];
  assert.equal(recoveredItem.attempts,2);assert.equal(recoveredItem.error,null);assert.equal(recoveredItem.result.error,null,'Successful recovery clears the previous transient failure');
  // Saving a paid result retries only the DB commit.
  await pool.query("CREATE SEQUENCE fail_save_seq; CREATE FUNCTION fail_save() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.result IS NOT NULL AND nextval('fail_save_seq')=1 THEN RAISE EXCEPTION 'injected save failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_save BEFORE UPDATE ON job_run_items FOR EACH ROW EXECUTE FUNCTION fail_save()");
  const beforeSave=calls;const saveRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await waitFor(async()=>(await request(`/api/job-runs/${saveRun.body.id}`,'GET',undefined,user)).body.status==='completed','save retry');
  assert.equal(calls,beforeSave+1,'DB retry must not make a second provider request');
  await pool.query('DROP TRIGGER fail_save ON job_run_items');
  providerMode='permanent';const beforeError=calls;
  const failed=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await waitFor(async()=>(await request(`/api/job-runs/${failed.body.id}`,'GET',undefined,user)).body.status==='failed','permanent provider error');
  assert.equal(calls,beforeError+1);
  // The retry cause is committed before backoff and survives worker interruption.
  providerMode='retryable';const beforeInterruption=calls;
  const interrupted=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  let recordedFailure='';
  await waitFor(async()=>{
    const item=(await pool.query("SELECT attempts,error FROM job_run_items WHERE run_id=$1 AND sku='a'",[interrupted.body.id])).rows[0];
    if(item.attempts===1&&item.error?.includes('HTTP 503')){recordedFailure=item.error;return true;}return false;
  },'durable transient provider failure');
  await stopWorker();stopWorker=undefined;
  assert.equal(calls,beforeInterruption+1,'Stopping during retry backoff prevents another dispatch');
  assert.match(recordedFailure,/QA attempt 1:.*HTTP 503.*Temporary provider outage/);
  assert.match(recordedFailure,/\[redacted\]/);assert.doesNotMatch(recordedFailure,/test-secret-only|sk-private-test|private-header|\n/);
  const interruptedHistory=(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body;
  assert.equal(interruptedHistory.items[0].error,recordedFailure);
  await pool.query("UPDATE job_run_items SET attempts=3 WHERE run_id=$1 AND sku='a'",[interrupted.body.id]);
  providerMode='success';stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body.status==='failed','exhausted recovery retains the provider failure');
  assert.equal(calls,beforeInterruption+1,'An exhausted resumed item never dispatches another paid request');
  const retainedFailure=(await request(`/api/job-runs/${interrupted.body.id}`,'GET',undefined,user)).body.items[0].error;
  assert.ok(retainedFailure.includes(recordedFailure));assert.match(retainedFailure,/fresh run/i);
  assert.doesNotMatch(retainedFailure,/test-secret-only|sk-private-test|private-header/);
  providerMode='wait';const beforeCancel=calls;
  const cancelled=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  assert.equal(cancelled.status,202,JSON.stringify(cancelled.body));
  await waitFor(async()=>calls>beforeCancel,'inflight cancel');
  assert.equal((await request(`/api/job-runs/${cancelled.body.id}/cancel`,'POST',{},user)).status,200);
  await waitFor(async()=>(await request(`/api/job-runs/${cancelled.body.id}`,'GET',undefined,user)).body.status==='cancelled','cancelled');
  assert.equal(calls,beforeCancel+1,'Cancel prevents dispatching the next SKU');
  await stopWorker();stopWorker=undefined;
  // Neither a restart nor a future retry may reset a consumed budget or deadline.
  const exhausted=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await pool.query("UPDATE job_run_items SET attempts=3 WHERE run_id=$1 AND sku='a'",[exhausted.body.id]);
  const beforeExhaustion=calls;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${exhausted.body.id}`,'GET',undefined,user)).body.status==='failed','exhausted attempts');
  assert.equal(calls,beforeExhaustion);
  const exhaustionError=(await request(`/api/job-runs/${exhausted.body.id}`,'GET',undefined,user)).body.items[0].error;
  assert.match(exhaustionError,/interrupted.*fresh run/i,'Without a saved cause, exhausted recovery explains interruption and a fresh rerun');
  await stopWorker();stopWorker=undefined;
  const expired=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  await pool.query("UPDATE job_run_items SET started_at=now()-interval '6 minutes' WHERE run_id=$1 AND sku='a'",[expired.body.id]);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${expired.body.id}`,'GET',undefined,user)).body.status==='failed','expired item deadline');
  assert.equal(calls,beforeExhaustion);
  await stopWorker();stopWorker=undefined;
  // Browser retrieval is independent of models; QA retains its durable settings snapshot.
  const productUrl='https://8.8.8.8/product?variant=42';
  assert.equal((await edit('b',{source:{sap:'Brand: TestBrand',url:productUrl},scraped_markdown:''})).status,200);
  const webRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  const snapshotConfig=(await pool.query('SELECT configuration FROM job_runs WHERE id=$1',[webRun.body.id])).rows[0].configuration;
  assert.ok(!('scrapperModelName' in snapshotConfig.settings));assert.ok(!('selectors' in snapshotConfig));
  assert.doesNotMatch(JSON.stringify(snapshotConfig),/test-secret-only|apiKey|sgai-.*-secret/);
  await request('/api/provider-settings','PUT',{...configured,modelName:'next/qa'},admin);
  providerMode='success';let offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${webRun.body.id}`,'GET',undefined,user)).body.status==='completed','snapshotted retrieval');
  await stopWorker();stopWorker=undefined;
  assert.deepEqual(providerRequests.slice(offset).map(payload=>payload.model),['deepseek/deepseek-v4.1-flash']);
  assert.equal(scrapeRequests.at(-1),productUrl);
  const qaRequest=providerRequests[offset];
  assert.equal(qaRequest.reasoning_effort,'low');assert.equal(qaRequest.max_tokens,10000);
  assert.deepEqual(qaRequest.response_format,{type:'json_object'});assert.ok(qaRequest.messages[0].content.includes(mappingRules));
  assert.match(qaRequest.messages[0].content,/SAP takes precedence/);
  const qaData=JSON.parse(qaRequest.messages[1].content);
  assert.equal(qaData.attribute_set,'TestSet');assert.equal(qaData.source_sap,'Brand: TestBrand');assert.equal(qaData.source_url,productUrl);
  assert.match(qaData.scraped_markdown,/Retrieved product/);
  assert.deepEqual(qaData.uploaded_template,{sku:'b',attributes__brand:'TestBrand',attributes__bullet_point_7:'Extra supplied bullet',custom_optional:''},'QA receives every original upload field without source-only columns');
  const webHistory=(await request(`/api/job-runs/${webRun.body.id}`,'GET',undefined,user)).body;
  assert.match(webHistory.items[1].result.scraped_markdown,/Retrieved product/);
  assert.doesNotMatch(JSON.stringify(webHistory),/sgai-.*-secret|apiKey/);
  assert.equal(webHistory.items[1].error,null);assert.equal(webHistory.items[1].result.qa_result.qa_status,'pass');
  assert.deepEqual(webHistory.items[1].result.qa_result.source_notes,{sap_used:true,url_used:true,source_conflicts:[]});
  assert.match((await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='b').scraped_markdown,/variant=42/);
  // Old job snapshots still retrieve with the browser without rewriting stored configuration.
  await pool.query("UPDATE sku_data SET scraped_markdown=NULL,scrape_status=NULL WHERE sku='b'");
  const legacyRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  await pool.query("UPDATE job_runs SET configuration=jsonb_set(configuration,'{settings}',(configuration->'settings')-'scrapperModelName') WHERE id=$1",[legacyRun.body.id]);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${legacyRun.body.id}`,'GET',undefined,user)).body.status==='completed','legacy retrieval defaults');
  await stopWorker();stopWorker=undefined;
  assert.equal(providerRequests[offset].model,'next/qa');
  assert.equal(providerRequests.length-offset,1);
  assert.equal(scrapeRequests.at(-1),productUrl);
  // Keep the actual browser failure when no other evidence exists; never spend QA tokens on it.
  await pool.query("UPDATE sku_data SET source=$1,scraped_markdown=NULL,scrape_status=NULL WHERE sku='b'",[JSON.stringify({url:productUrl})]);
  scrapeBlocked=true;
  const blockedRun=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'b'},user);
  offset=providerRequests.length;stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${blockedRun.body.id}`,'GET',undefined,user)).body.status==='failed','blocked page retains its browser error');
  await stopWorker();stopWorker=undefined;scrapeBlocked=false;
  const blockedItem=(await request(`/api/job-runs/${blockedRun.body.id}`,'GET',undefined,user)).body.items.find((item:any)=>item.sku==='b');
  assert.match(blockedItem.error,/website blocked browser access/);
  assert.equal(blockedItem.result.scrape_status,'failed');
  assert.equal(providerRequests.length,offset,'No QA request without usable source evidence');
  // Retrieval is committed before QA; later model failure or cancellation cannot erase it.
  await request('/api/catalog','POST',[{...sku('url-only'),source:{url:productUrl}}],user);
  assert.equal((await request('/api/jobs','POST',{id:'url-only-job',name:'URL-only job',skus:['url-only'],attribute_set:'TestSet'},user)).status,201);
  providerMode='permanent';
  const failureAfterScrape=await request('/api/jobs/url-only-job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${failureAfterScrape.body.id}`,'GET',undefined,user)).body.status==='failed','QA failure after committed scrape');
  await stopWorker();stopWorker=undefined;
  const savedEvidence=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='url-only');
  assert.match(savedEvidence.scraped_markdown,/Retrieved product/);assert.equal(savedEvidence.scrape_status,'success');
  assert.equal(savedEvidence.revision,1);assert.equal(savedEvidence.scrape_metadata.method,'browser');
  const savedItem=(await pool.query('SELECT revision,snapshot FROM job_run_items WHERE run_id=$1',[failureAfterScrape.body.id])).rows[0];
  assert.equal(savedItem.revision,savedEvidence.revision);assert.equal(savedItem.snapshot.scraped_markdown,savedEvidence.scraped_markdown);
  const cancelUrl='https://8.8.8.8/new-product';
  await edit('url-only',{source:{url:cancelUrl}});
  providerMode='wait';const callsBeforeCancel=calls;
  const cancelAfterScrape=await request('/api/jobs/url-only-job/runs','POST',{requestId:randomUUID(),mode:'all'},user);
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>calls>callsBeforeCancel,'QA started after fresh scrape');
  const beforeCancelEvidence=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='url-only');
  assert.equal(beforeCancelEvidence.scrape_metadata.requestedUrl,cancelUrl);
  assert.equal(beforeCancelEvidence.revision,3,'Source edit and new scrape each advance evidence revision');
  await request(`/api/job-runs/${cancelAfterScrape.body.id}/cancel`,'POST',{},user);
  await waitFor(async()=>(await request(`/api/job-runs/${cancelAfterScrape.body.id}`,'GET',undefined,user)).body.status==='cancelled','Cancellation after committed scrape');
  await stopWorker();stopWorker=undefined;
  assert.equal((await pool.query("SELECT scraped_markdown FROM sku_data WHERE sku='url-only'")).rows[0].scraped_markdown,beforeCancelEvidence.scraped_markdown);
  providerMode='success';
  // Imported legacy reviews are rerun; trusted skipped reviews have their own durable result.
  const forgedQa={qa_status:'warning',issues:[{field:'brand',suggested_fix:'Forged brand'}]};
  const legacyRaw={...sku('a').raw_row,qa_result:forgedQa};
  await pool.query("UPDATE sku_data SET raw_row=$1,qa_result=NULL,export_data=$2,status='completed',error=NULL WHERE sku='a'",[JSON.stringify(legacyRaw),JSON.stringify(forgedQa)]);
  const trustedB=history.items[1].result;
  await pool.query("UPDATE sku_data SET qa_result=$1,export_data=$2,qa_revision=revision,status='completed',error=NULL WHERE sku='b'",[JSON.stringify(trustedB.qa_result),JSON.stringify(trustedB.export_data)]);
  const unverified=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='a');
  assert.equal(unverified.status,'ready');assert.equal(unverified.qa_result,null);
  assert.equal(unverified.export_data,null);assert.equal(unverified.error,'Legacy review is unverified; rerun QA.');
  assert.ok(!Object.hasOwn(unverified.raw_row,'qa_result'));
  await edit('a',{source:sku('a').source});
  assert.equal((await pool.query("SELECT error FROM sku_data WHERE sku='a'")).rows[0].error,null,'Raw QA never triggers evidence-edit invalidation');
  const unfinished=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'unfinished'},user);
  assert.equal(unfinished.status,202);
  assert.equal(unfinished.body.items[0].status,'queued');
  assert.equal(unfinished.body.items[1].status,'skipped');
  assert.deepEqual(unfinished.body.items[1].result.qa_result,trustedB.qa_result);
  assert.ok(!Object.hasOwn(unfinished.body.items[1].snapshot,'qa_result'));
  const beforeLegacyCalls=calls;
  const beforeLegacyUsage=(await pool.query("SELECT tokens_used FROM jobs WHERE id='job'")).rows[0].tokens_used.total_tokens;
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${unfinished.body.id}`,'GET',undefined,user)).body.status==='completed','legacy review rerun');
  await stopWorker();stopWorker=undefined;
  assert.equal(calls,beforeLegacyCalls+1,'Only the unverified review is sent to the mocked provider');
  const reviewed=(await request(`/api/job-runs/${unfinished.body.id}`,'GET',undefined,user)).body;
  assert.equal(reviewed.items[0].result.qa_result.qa_status,'pass');
  assert.deepEqual(reviewed.items[1].result.qa_result,trustedB.qa_result);
  const savedLegacy=(await pool.query("SELECT raw_row,qa_result FROM sku_data WHERE sku='a'")).rows[0];
  assert.deepEqual(savedLegacy.raw_row,legacyRaw,'Reruns preserve original stored legacy data');
  assert.equal(savedLegacy.qa_result.qa_status,'pass');
  const afterLegacyJob=(await pool.query("SELECT status,tokens_used FROM jobs WHERE id='job'")).rows[0];
  assert.equal(afterLegacyJob.status,'completed');
  assert.equal(afterLegacyJob.tokens_used.total_tokens,beforeLegacyUsage+15,'Skipped prior reviews do not charge usage twice');
  assert.ok(!Object.hasOwn((await pool.query("SELECT raw_row FROM sku_data WHERE sku='b'")).rows[0].raw_row,'qa_result'),'New worker reviews are never mirrored into raw rows');
  await edit('a',{source:{sap:'Changed after genuine review'}});
  const staleReview=(await request('/api/catalog','GET',undefined,user)).body.find((row:any)=>row.sku==='a');
  assert.equal(staleReview.qa_stale,true);assert.equal(staleReview.qa_result,null);assert.equal(staleReview.export_data,null);
  assert.ok((await pool.query("SELECT qa_result FROM sku_data WHERE sku='a'")).rows[0].qa_result,'Invalidation preserves the stored genuine prior review');
  assert.deepEqual((await request(`/api/job-runs/${unfinished.body.id}`,'GET',undefined,user)).body.items[0].result,reviewed.items[0].result,'Genuine history survives later catalog edits');
  // An older skipped snapshot, even with top-level QA, is evidence only.
  const snapshotOnly=await request('/api/jobs/job/runs','POST',{requestId:randomUUID(),mode:'single',sku:'a'},user);
  const oldSnapshot={...trustedB,raw_row:{...trustedB.raw_row,qa_result:forgedQa}};
  await pool.query("UPDATE job_run_items SET snapshot=$2,result=NULL WHERE run_id=$1 AND sku='b'",[snapshotOnly.body.id,JSON.stringify(oldSnapshot)]);
  const oldItem=(await request(`/api/job-runs/${snapshotOnly.body.id}`,'GET',undefined,user)).body.items[1];
  assert.equal(oldItem.result,null);assert.equal(oldItem.snapshot.status,'ready');
  assert.equal(oldItem.snapshot.error,'Legacy review is unverified; rerun QA.');
  for(const key of ['qa_result','export_data','tokensUsed','timeTaken','last_job_id'])assert.ok(!Object.hasOwn(oldItem.snapshot,key));
  assert.ok(!Object.hasOwn(oldItem.snapshot.raw_row,'qa_result'));
  assert.deepEqual((await pool.query("SELECT snapshot FROM job_run_items WHERE run_id=$1 AND sku='b'",[snapshotOnly.body.id])).rows[0].snapshot,oldSnapshot,'Reading history never rewrites legacy snapshots');
  stopWorker=startJobWorker(pool,scrape);
  await waitFor(async()=>(await request(`/api/job-runs/${snapshotOnly.body.id}`,'GET',undefined,user)).body.status==='completed','snapshot-only history completion');
  await stopWorker();stopWorker=undefined;
  assert.equal((await pool.query("SELECT status FROM jobs WHERE id='job'")).rows[0].status,'pending','Unverified skipped snapshots cannot complete a job');
  await initializeDatabase(pool); // Existing populated records remain readable after restart migrations.
  // Clear remains all-or-nothing even if catalog deletion fails after deleting jobs.
  await pool.query("CREATE FUNCTION fail_clear() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected clear failure'; END $$; CREATE TRIGGER fail_clear BEFORE DELETE ON sku_data FOR EACH ROW EXECUTE FUNCTION fail_clear()");
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,503);
  assert.deepEqual((await request('/api/jobs','GET',undefined,user)).body.map((job:any)=>job.id).sort(),['job','url-only-job']);
  await pool.query('DROP TRIGGER fail_clear ON sku_data');
  assert.equal((await request('/api/data','DELETE',undefined,admin)).status,200);
  assert.equal((await request('/api/jobs','GET',undefined,user)).body.length,0);
  await request('/api/users/user','PUT',{password:'replacement-test-password'},admin);
  assert.equal((await request('/api/catalog','GET',undefined,user)).status,401);
  await pool.query('UPDATE sessions SET expires_at=now()-interval \'1 second\' WHERE token_hash=$1',[hashSessionToken(other.split('=')[1])]);
  assert.equal((await request('/api/catalog','GET',undefined,other)).status,401);
  await request('/api/auth/logout','POST',undefined,admin);
  assert.equal((await request('/api/catalog','GET',undefined,admin)).status,401);
  // Retired selector data never blocks startup and is left untouched.
  await pool.query("CREATE TABLE site_selectors(id text PRIMARY KEY,website text,selectors text); INSERT INTO site_selectors VALUES('one','Example.com','main'),('two','www.example.com','article')");
  await initializeDatabase(pool);await verifySchema(pool);
  assert.equal((await pool.query('SELECT * FROM site_selectors')).rowCount,2);
  assert.equal((await pool.query("SELECT website FROM site_selectors WHERE id='one'")).rows[0].website,'Example.com');
  console.log('Security/database checks passed: sessions, roles, atomic saves, recovery, ownership, cancellation, budgets, model snapshots, retrieval, and preserved legacy data.');
} finally {
  await stopWorker?.();await stopSecond?.();server.closeAllConnections();provider.closeAllConnections();
  await Promise.all([new Promise<void>(resolve=>server.close(()=>resolve())),new Promise<void>(resolve=>provider.close(()=>resolve()))]);
  await pool.end();await root.query(`DROP SCHEMA ${namespace} CASCADE`);await root.end();
}
