import assert from 'node:assert/strict';
import { normalizeSettings, editableSettings, DEFAULT_SETTINGS } from '../lib/providerSettings';
const settings=normalizeSettings({apiKey:'must-not-survive',maxConcurrency:99,maxRetries:99,modelName:'test',maxTokens:10000} as any);
assert.ok(!('apiKey' in settings));
assert.equal(settings.maxConcurrency,1);
assert.equal(settings.maxRetries,2);
assert.equal(settings.maxTokens,10000);
assert.equal(normalizeSettings({maxTokens:-1}).maxTokens,4096);
assert.equal(normalizeSettings({maxPageContentLength:0}).maxPageContentLength,40000);
assert.equal(normalizeSettings({qaAgentMemory:' '}).qaAgentMemory,DEFAULT_SETTINGS.qaAgentMemory);
assert.ok(!('baseUrl' in editableSettings(settings)));
console.log('Server settings normalization checks passed.');
